package client

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const defaultDNSSuffix = "tela"

// defaultProfileName returns the name of the first profile found in
// the profiles directory, or "" if none exist. This mirrors TV's
// fallback logic so 'tela dns hosts' works without -profile.
func defaultProfileName() string {
	dir := profilesDir()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return ""
	}
	for _, e := range entries {
		if !e.IsDir() && filepath.Ext(e.Name()) == ".yaml" {
			return strings.TrimSuffix(e.Name(), ".yaml")
		}
	}
	return ""
}

func cmdDNS(args []string) {
	if len(args) == 0 {
		printDNSUsage()
		os.Exit(1)
	}

	switch args[0] {
	case "hosts":
		cmdDNSHosts(args[1:])
	case "help", "-h", "--help":
		printDNSUsage()
	default:
		fmt.Fprintf(os.Stderr, "Unknown dns subcommand: %s\n\n", args[0])
		printDNSUsage()
		os.Exit(1)
	}
}

func printDNSUsage() {
	fmt.Fprintf(os.Stderr, `tela dns -- Local name resolution

Subcommands:
  hosts  [-profile <name>] [-suffix <domain>]
         Print hosts file entries for all machines in a profile.

         Append the output to your hosts file to enable name-based access:
           Linux/macOS:  tela dns hosts >> /etc/hosts
           Windows:      tela dns hosts >> C:\Windows\System32\drivers\etc\hosts

         The suffix defaults to "tela". Use -suffix "" for bare machine names.

Examples:
  tela dns hosts                              # use default profile (telavisor)
  tela dns hosts -profile myprofile           # use a specific profile
  tela dns hosts -suffix local                # barn.local instead of barn.tela
  tela dns hosts -suffix ""                   # bare names: barn, work-laptop
`)
}

func cmdDNSHosts(args []string) {
	fs := flag.NewFlagSet("dns hosts", flag.ExitOnError)
	profileName := fs.String("profile", "", "Profile name (default: first available)")
	suffix := fs.String("suffix", defaultDNSSuffix, "Domain suffix (empty for bare names)")
	fs.Parse(args)

	name := *profileName
	if name == "" {
		name = defaultProfileName()
	}
	if name == "" {
		fmt.Fprintln(os.Stderr, "Error: no profiles found in "+profilesDir())
		os.Exit(1)
	}

	profile, err := loadProfile(name)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	lbPrefix := profile.DNS.LoopbackPrefix
	if lbPrefix == "" {
		lbPrefix = "127.88"
	}

	// Collect unique machine entries, respecting per-machine address overrides.
	type entry struct {
		addr string
		name string
	}
	seen := make(map[string]bool)
	var entries []entry
	for _, conn := range profile.Connections {
		hubURL := mustResolveHub(conn.Hub)
		machine := conn.Machine
		if hubURL == "" || machine == "" {
			continue
		}
		if seen[machine] {
			continue
		}
		seen[machine] = true

		addr := conn.Address
		if addr == "" {
			addr = LoopbackAddr(lbPrefix, hubURL, machine)
		}

		name := machine
		if *suffix != "" {
			name = machine + "." + *suffix
		}
		entries = append(entries, entry{addr: addr, name: name})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})

	fmt.Println("# Tela local names -- generated by 'tela dns hosts'")
	for _, e := range entries {
		fmt.Printf("%-18s %s\n", e.addr, e.name)
	}
}
