// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHub(arg1, arg2) {
  return window['go']['main']['App']['AddHub'](arg1, arg2);
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function Disconnect(arg1, arg2) {
  return window['go']['main']['App']['Disconnect'](arg1, arg2);
}

export function DockerGetToken(arg1, arg2) {
  return window['go']['main']['App']['DockerGetToken'](arg1, arg2);
}

export function DockerListContainers() {
  return window['go']['main']['App']['DockerListContainers']();
}

export function EnsureTool(arg1) {
  return window['go']['main']['App']['EnsureTool'](arg1);
}

export function GetCommandLog() {
  return window['go']['main']['App']['GetCommandLog']();
}

export function GetConnectionOutput(arg1, arg2) {
  return window['go']['main']['App']['GetConnectionOutput'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetHubStatus(arg1) {
  return window['go']['main']['App']['GetHubStatus'](arg1);
}

export function GetKnownHubs() {
  return window['go']['main']['App']['GetKnownHubs']();
}

export function GetStoredToken(arg1) {
  return window['go']['main']['App']['GetStoredToken'](arg1);
}

export function PortalSignIn(arg1, arg2, arg3) {
  return window['go']['main']['App']['PortalSignIn'](arg1, arg2, arg3);
}

export function RemoveHub(arg1) {
  return window['go']['main']['App']['RemoveHub'](arg1);
}
