// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPortal(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CheckTools():Promise<Array<main.ToolStatus>>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetCommandLog():Promise<Array<main.CommandLogEntry>>;

export function GetConnectionOutput(arg1:string,arg2:string):Promise<string>;

export function GetConnections():Promise<Array<main.ActiveConnection>>;

export function GetHubStatus(arg1:string):Promise<Record<string, any>>;

export function GetOrgHubs(arg1:string):Promise<Array<Record<string, any>>>;

export function GetOrganizations():Promise<Array<Record<string, any>>>;

export function GetPortals():Promise<Array<main.PortalConnection>>;

export function GetStoredToken(arg1:string):Promise<string>;

export function InstallTool(arg1:string,arg2:string):Promise<string>;

export function LatestRelease():Promise<string>;

export function RemovePortal(arg1:string):Promise<void>;

export function SignIn(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StoreToken(arg1:string,arg2:string):Promise<void>;
