// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHub(arg1, arg2) {
  return window['go']['main']['App']['AddHub'](arg1, arg2);
}

export function AddRemote(arg1, arg2) {
  return window['go']['main']['App']['AddRemote'](arg1, arg2);
}

export function AdminAPICall(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AdminAPICall'](arg1, arg2, arg3, arg4);
}

export function AdminCreateToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminCreateToken'](arg1, arg2, arg3);
}

export function AdminDeleteToken(arg1, arg2) {
  return window['go']['main']['App']['AdminDeleteToken'](arg1, arg2);
}

export function AdminGeneratePairCode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AdminGeneratePairCode'](arg1, arg2, arg3, arg4, arg5);
}

export function AdminListAccess(arg1) {
  return window['go']['main']['App']['AdminListAccess'](arg1);
}

export function AdminListPortals(arg1) {
  return window['go']['main']['App']['AdminListPortals'](arg1);
}

export function AdminListTokens(arg1) {
  return window['go']['main']['App']['AdminListTokens'](arg1);
}

export function AdminRenameAccess(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AdminRenameAccess'](arg1, arg2, arg3, arg4);
}

export function AdminRevokeMachineAccess(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AdminRevokeMachineAccess'](arg1, arg2, arg3, arg4);
}

export function AdminRotateToken(arg1, arg2) {
  return window['go']['main']['App']['AdminRotateToken'](arg1, arg2);
}

export function AdminSetMachineAccess(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AdminSetMachineAccess'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AssignLocalPort(arg1) {
  return window['go']['main']['App']['AssignLocalPort'](arg1);
}

export function AttachToExisting() {
  return window['go']['main']['App']['AttachToExisting']();
}

export function BrowseBinPath() {
  return window['go']['main']['App']['BrowseBinPath']();
}

export function CheckForUpdatesNow() {
  return window['go']['main']['App']['CheckForUpdatesNow']();
}

export function ClearCredentialStore() {
  return window['go']['main']['App']['ClearCredentialStore']();
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function ConfirmDisconnect() {
  return window['go']['main']['App']['ConfirmDisconnect']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectControlWS() {
  return window['go']['main']['App']['ConnectControlWS']();
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Detach() {
  return window['go']['main']['App']['Detach']();
}

export function DetectCredentialType(arg1) {
  return window['go']['main']['App']['DetectCredentialType'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DisconnectControlWS() {
  return window['go']['main']['App']['DisconnectControlWS']();
}

export function DockerGetToken(arg1, arg2) {
  return window['go']['main']['App']['DockerGetToken'](arg1, arg2);
}

export function DockerListContainers() {
  return window['go']['main']['App']['DockerListContainers']();
}

export function EnsureTool(arg1) {
  return window['go']['main']['App']['EnsureTool'](arg1);
}

export function ExportProfile() {
  return window['go']['main']['App']['ExportProfile']();
}

export function FileShareDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FileShareDownload'](arg1, arg2, arg3, arg4);
}

export function FileShareRequest(arg1, arg2) {
  return window['go']['main']['App']['FileShareRequest'](arg1, arg2);
}

export function FileShareUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FileShareUpload'](arg1, arg2, arg3, arg4);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetAgentChannelInfo(arg1, arg2) {
  return window['go']['main']['App']['GetAgentChannelInfo'](arg1, arg2);
}

export function GetAgentConfig(arg1, arg2) {
  return window['go']['main']['App']['GetAgentConfig'](arg1, arg2);
}

export function GetAgentList() {
  return window['go']['main']['App']['GetAgentList']();
}

export function GetAgentLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAgentLogs'](arg1, arg2, arg3);
}

export function GetAgentSources(arg1, arg2) {
  return window['go']['main']['App']['GetAgentSources'](arg1, arg2);
}

export function GetBinStatus() {
  return window['go']['main']['App']['GetBinStatus']();
}

export function GetCLIPath() {
  return window['go']['main']['App']['GetCLIPath']();
}

export function GetChannelSources() {
  return window['go']['main']['App']['GetChannelSources']();
}

export function GetClientChannel() {
  return window['go']['main']['App']['GetClientChannel']();
}

export function GetClientSources() {
  return window['go']['main']['App']['GetClientSources']();
}

export function GetCommandLog() {
  return window['go']['main']['App']['GetCommandLog']();
}

export function GetConnectionState() {
  return window['go']['main']['App']['GetConnectionState']();
}

export function GetControlConnections() {
  return window['go']['main']['App']['GetControlConnections']();
}

export function GetControlServices() {
  return window['go']['main']['App']['GetControlServices']();
}

export function GetControlStatus() {
  return window['go']['main']['App']['GetControlStatus']();
}

export function GetCurrentProfile() {
  return window['go']['main']['App']['GetCurrentProfile']();
}

export function GetDefaultBinPath() {
  return window['go']['main']['App']['GetDefaultBinPath']();
}

export function GetHubChannelInfo(arg1) {
  return window['go']['main']['App']['GetHubChannelInfo'](arg1);
}

export function GetHubHistory(arg1) {
  return window['go']['main']['App']['GetHubHistory'](arg1);
}

export function GetHubInfo(arg1) {
  return window['go']['main']['App']['GetHubInfo'](arg1);
}

export function GetHubLogs(arg1, arg2) {
  return window['go']['main']['App']['GetHubLogs'](arg1, arg2);
}

export function GetHubSources(arg1) {
  return window['go']['main']['App']['GetHubSources'](arg1);
}

export function GetHubStatus(arg1) {
  return window['go']['main']['App']['GetHubStatus'](arg1);
}

export function GetKnownHubs() {
  return window['go']['main']['App']['GetKnownHubs']();
}

export function GetLocalInstances() {
  return window['go']['main']['App']['GetLocalInstances']();
}

export function GetMachineCapabilities() {
  return window['go']['main']['App']['GetMachineCapabilities']();
}

export function GetMountConfig() {
  return window['go']['main']['App']['GetMountConfig']();
}

export function GetProfileMTU() {
  return window['go']['main']['App']['GetProfileMTU']();
}

export function GetProfilePath() {
  return window['go']['main']['App']['GetProfilePath']();
}

export function GetProfileYAML() {
  return window['go']['main']['App']['GetProfileYAML']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStoredToken(arg1) {
  return window['go']['main']['App']['GetStoredToken'](arg1);
}

export function GetTokenRole(arg1) {
  return window['go']['main']['App']['GetTokenRole'](arg1);
}

export function GetToolVersions() {
  return window['go']['main']['App']['GetToolVersions']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function GetUpdateVersion() {
  return window['go']['main']['App']['GetUpdateVersion']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasUpdate() {
  return window['go']['main']['App']['HasUpdate']();
}

export function HubCapabilities(arg1) {
  return window['go']['main']['App']['HubCapabilities'](arg1);
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function InstallAsService() {
  return window['go']['main']['App']['InstallAsService']();
}

export function InstallAsUserTask() {
  return window['go']['main']['App']['InstallAsUserTask']();
}

export function InstallBinary(arg1) {
  return window['go']['main']['App']['InstallBinary'](arg1);
}

export function IsAttached() {
  return window['go']['main']['App']['IsAttached']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function IsModalOpen() {
  return window['go']['main']['App']['IsModalOpen']();
}

export function IsMountRunning() {
  return window['go']['main']['App']['IsMountRunning']();
}

export function IsPackageManaged() {
  return window['go']['main']['App']['IsPackageManaged']();
}

export function IsQuitting() {
  return window['go']['main']['App']['IsQuitting']();
}

export function ListCredentials() {
  return window['go']['main']['App']['ListCredentials']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListRemotes() {
  return window['go']['main']['App']['ListRemotes']();
}

export function LoadProfile() {
  return window['go']['main']['App']['LoadProfile']();
}

export function LogAdminGET(arg1, arg2) {
  return window['go']['main']['App']['LogAdminGET'](arg1, arg2);
}

export function LoopbackAddr(arg1, arg2) {
  return window['go']['main']['App']['LoopbackAddr'](arg1, arg2);
}

export function MigrateAllProfiles() {
  return window['go']['main']['App']['MigrateAllProfiles']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function PairWithCode(arg1, arg2) {
  return window['go']['main']['App']['PairWithCode'](arg1, arg2);
}

export function PortalDeviceAuthComplete(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PortalDeviceAuthComplete'](arg1, arg2, arg3, arg4);
}

export function PortalDeviceAuthStart(arg1) {
  return window['go']['main']['App']['PortalDeviceAuthStart'](arg1);
}

export function PortalListSources() {
  return window['go']['main']['App']['PortalListSources']();
}

export function PortalRemoveSource(arg1) {
  return window['go']['main']['App']['PortalRemoveSource'](arg1);
}

export function PortalRenameSource(arg1, arg2) {
  return window['go']['main']['App']['PortalRenameSource'](arg1, arg2);
}

export function PortalSetSourceEnabled(arg1, arg2) {
  return window['go']['main']['App']['PortalSetSourceEnabled'](arg1, arg2);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshBinStatus() {
  return window['go']['main']['App']['RefreshBinStatus']();
}

export function ReleaseLocalPort(arg1) {
  return window['go']['main']['App']['ReleaseLocalPort'](arg1);
}

export function RemoveAgentSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveAgentSource'](arg1, arg2, arg3);
}

export function RemoveClientSource(arg1) {
  return window['go']['main']['App']['RemoveClientSource'](arg1);
}

export function RemoveCredential(arg1) {
  return window['go']['main']['App']['RemoveCredential'](arg1);
}

export function RemoveHub(arg1) {
  return window['go']['main']['App']['RemoveHub'](arg1);
}

export function RemoveHubSource(arg1, arg2) {
  return window['go']['main']['App']['RemoveHubSource'](arg1, arg2);
}

export function RemoveRemote(arg1) {
  return window['go']['main']['App']['RemoveRemote'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function ResolveAllPorts(arg1) {
  return window['go']['main']['App']['ResolveAllPorts'](arg1);
}

export function RestartAgent(arg1, arg2) {
  return window['go']['main']['App']['RestartAgent'](arg1, arg2);
}

export function RestartHub(arg1) {
  return window['go']['main']['App']['RestartHub'](arg1);
}

export function RestartToUpdate() {
  return window['go']['main']['App']['RestartToUpdate']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveHubsSidebarWidth(arg1) {
  return window['go']['main']['App']['SaveHubsSidebarWidth'](arg1);
}

export function SaveLastSelectedHub(arg1) {
  return window['go']['main']['App']['SaveLastSelectedHub'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSidebarWidth(arg1) {
  return window['go']['main']['App']['SaveSidebarWidth'](arg1);
}

export function SaveTerminalOutput(arg1) {
  return window['go']['main']['App']['SaveTerminalOutput'](arg1);
}

export function SendControlCommand(arg1) {
  return window['go']['main']['App']['SendControlCommand'](arg1);
}

export function ServiceStart() {
  return window['go']['main']['App']['ServiceStart']();
}

export function ServiceStop() {
  return window['go']['main']['App']['ServiceStop']();
}

export function SetAgentChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAgentChannel'](arg1, arg2, arg3, arg4);
}

export function SetAgentConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAgentConfig'](arg1, arg2, arg3);
}

export function SetAgentSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAgentSource'](arg1, arg2, arg3, arg4);
}

export function SetClientChannel(arg1, arg2) {
  return window['go']['main']['App']['SetClientChannel'](arg1, arg2);
}

export function SetClientSource(arg1, arg2) {
  return window['go']['main']['App']['SetClientSource'](arg1, arg2);
}

export function SetHubChannel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetHubChannel'](arg1, arg2, arg3);
}

export function SetHubSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetHubSource'](arg1, arg2, arg3);
}

export function SetModalOpen(arg1) {
  return window['go']['main']['App']['SetModalOpen'](arg1);
}

export function SetMountConfig(arg1) {
  return window['go']['main']['App']['SetMountConfig'](arg1);
}

export function SetProfileMTU(arg1) {
  return window['go']['main']['App']['SetProfileMTU'](arg1);
}

export function SetVerbose(arg1) {
  return window['go']['main']['App']['SetVerbose'](arg1);
}

export function ShouldAutoConnect() {
  return window['go']['main']['App']['ShouldAutoConnect']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartMount() {
  return window['go']['main']['App']['StartMount']();
}

export function StopMount() {
  return window['go']['main']['App']['StopMount']();
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function TryAttach() {
  return window['go']['main']['App']['TryAttach']();
}

export function UninstallService() {
  return window['go']['main']['App']['UninstallService']();
}

export function UninstallUserTask() {
  return window['go']['main']['App']['UninstallUserTask']();
}

export function UpdateAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAgent'](arg1, arg2, arg3);
}

export function UpdateHub(arg1, arg2) {
  return window['go']['main']['App']['UpdateHub'](arg1, arg2);
}

export function UpdateLocalService(arg1) {
  return window['go']['main']['App']['UpdateLocalService'](arg1);
}

export function UpdateServiceAgent() {
  return window['go']['main']['App']['UpdateServiceAgent']();
}

export function UserTaskStart() {
  return window['go']['main']['App']['UserTaskStart']();
}

export function UserTaskStop() {
  return window['go']['main']['App']['UserTaskStop']();
}

export function ValidateBinPath(arg1) {
  return window['go']['main']['App']['ValidateBinPath'](arg1);
}
