// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHub(arg1:string,arg2:string):Promise<void>;

export function AssignLocalPort(arg1:number):Promise<number>;

export function Connect(arg1:string):Promise<string>;

export function Disconnect():Promise<void>;

export function DockerGetToken(arg1:string,arg2:string):Promise<string>;

export function DockerListContainers():Promise<Array<string>>;

export function EnsureTool(arg1:string):Promise<string>;

export function GetCommandLog():Promise<Array<main.CommandLogEntry>>;

export function GetConnectionState():Promise<main.ConnectionState>;

export function GetControlStatus():Promise<Record<string, any>>;

export function GetHubStatus(arg1:string):Promise<main.HubStatus>;

export function GetKnownHubs():Promise<Array<main.KnownHub>>;

export function GetStoredToken(arg1:string):Promise<string>;

export function GetUpdateVersion():Promise<string>;

export function HasUpdate():Promise<boolean>;

export function LoadProfile():Promise<Array<main.ProfileConnection>>;

export function ReleaseLocalPort(arg1:number):Promise<void>;

export function RemoveHub(arg1:string):Promise<void>;

export function ResolveAllPorts(arg1:string):Promise<Array<main.PortAssignment>>;

export function RestartToUpdate():Promise<void>;

export function SaveProfile(arg1:string):Promise<string>;

export function SetVerbose(arg1:boolean):Promise<void>;
