package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/cookiejar"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"

	"log"

	wailsRuntime "github.com/wailsapp/wails/v2/pkg/runtime"

	"github.com/paulmooreparks/tela/internal/credstore"
	"gopkg.in/yaml.v3"
)

// version is set at build time via -ldflags "-X main.version=..."
var version = "dev"

// App is the main application struct exposed to the frontend via Wails bindings.
type App struct {
	ctx context.Context

	mu            sync.Mutex
	cmdLog        []CommandLogEntry
	httpClient    *http.Client
	assignedPorts map[int]bool // ports already assigned in this session

	// Profile-based connection state
	telaProcess *os.Process
	telaOutput  string
	connected   bool

	// Self-update state
	updatePending bool
	updateVersion string
}

// CommandLogEntry records a CLI command generated by the GUI.
type CommandLogEntry struct {
	Time        string `json:"time"`
	Description string `json:"description"`
	Command     string `json:"command"`
}

// KnownHub is a hub the GUI knows about from the local registry.
type KnownHub struct {
	Name     string `json:"name"`
	URL      string `json:"url"`
	HasToken bool   `json:"hasToken"`
	Source   string `json:"source"` // "credentials", "hubs"
}

// HubStatus is the status of a hub and its machines.
type HubStatus struct {
	Online   bool            `json:"online"`
	HubName  string          `json:"hubName"`
	Machines []MachineStatus `json:"machines"`
	Error    string          `json:"error,omitempty"`
}

// MachineStatus is the status of a machine on a hub.
type MachineStatus struct {
	ID             string        `json:"id"`
	Hostname       string        `json:"hostname"`
	OS             string        `json:"os"`
	AgentConnected bool          `json:"agentConnected"`
	SessionCount   int           `json:"sessionCount"`
	LastSeen       string        `json:"lastSeen"`
	Services       []ServiceInfo `json:"services"`
}

// ServiceInfo describes a service on a machine.
type ServiceInfo struct {
	Name  string `json:"name"`
	Port  int    `json:"port"`
	Proto string `json:"proto"`
}

// ProfileConnection represents one connection entry in the profile YAML.
type ProfileConnection struct {
	Hub      string           `yaml:"hub" json:"hub"`
	Machine  string           `yaml:"machine" json:"machine"`
	Token    string           `yaml:"token,omitempty" json:"token,omitempty"`
	Services []ProfileService `yaml:"services" json:"services"`
}

// ProfileService represents one service in a profile connection.
type ProfileService struct {
	Name  string `yaml:"name" json:"name"`
	Local int    `yaml:"local" json:"local"`
}

// Profile is the top-level profile YAML structure.
type Profile struct {
	Connections []ProfileConnection `yaml:"connections" json:"connections"`
}

// ConnectionState is the current connection state returned to the frontend.
type ConnectionState struct {
	Connected   bool               `json:"connected"`
	Pid         int                `json:"pid"`
	Output      string             `json:"output"`
	Connections []ProfileConnection `json:"connections"`
}

// NewApp creates a new App instance.
func NewApp() *App {
	jar, _ := cookiejar.New(nil)
	return &App{
		httpClient: &http.Client{
			Timeout: 15 * time.Second,
			Jar:     jar,
		},
		assignedPorts: make(map[int]bool),
	}
}

func (a *App) startup(ctx context.Context) {
	a.ctx = ctx

	// Apply any pending self-update from a previous run
	a.applyPendingSelfUpdate()

	// Set up system tray icon
	a.setupTray()

	// Check for updates (respects AutoCheckUpdates setting)
	settings := a.GetSettings()
	if settings.AutoCheckUpdates {
		go a.checkForUpdates()
	}
}

// checkForUpdates checks if any managed binary (telagui or tela CLI) is
// behind the latest GitHub release. If so, sets updatePending but does NOT
// auto-download. The user clicks "Restart to Update" to trigger the update.
// Exception: if tela CLI is not installed at all, it is downloaded immediately.
func (a *App) checkForUpdates() {
	latest, err := a.latestRelease()
	if err != nil {
		return // offline
	}

	needsUpdate := false

	// Check telagui version
	if version != latest {
		needsUpdate = true
	}

	// Check tela CLI version
	bin := "tela"
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	localPath := filepath.Join(telaInstallDir(), bin)

	if _, err := os.Stat(localPath); err != nil {
		// tela not installed -- download it now (first run)
		a.logCommand("Install tela "+latest, "# first run, downloading tela CLI")
		a.installTool("tela", latest)
	} else {
		// tela exists -- check version
		cmd := exec.Command(localPath, "version")
		hideConsoleWindow(cmd)
		out, _ := cmd.CombinedOutput()
		parts := strings.Fields(strings.TrimSpace(string(out)))
		if len(parts) >= 2 && parts[1] != latest {
			needsUpdate = true
		}
	}

	if needsUpdate {
		a.mu.Lock()
		a.updatePending = true
		a.updateVersion = latest
		a.mu.Unlock()
	}
}

// isPackageManaged returns true if telagui was installed via a package manager
// (deb, rpm, msi, dmg). In that case, self-update is disabled and the user
// should update via their package manager.
func isPackageManaged() bool {
	exe := selfExePath()
	if exe == "" {
		return false
	}
	// Linux: installed to /usr/bin or /usr/local/bin by deb/rpm
	if strings.HasPrefix(exe, "/usr/bin/") || strings.HasPrefix(exe, "/usr/local/bin/") {
		return true
	}
	// macOS: installed to /Applications
	if strings.HasPrefix(exe, "/Applications/") {
		return true
	}
	// Windows: installed to Program Files
	pf := os.Getenv("ProgramFiles")
	pfx86 := os.Getenv("ProgramFiles(x86)")
	if pf != "" && strings.HasPrefix(strings.ToLower(exe), strings.ToLower(pf)) {
		return true
	}
	if pfx86 != "" && strings.HasPrefix(strings.ToLower(exe), strings.ToLower(pfx86)) {
		return true
	}
	return false
}

// selfExePath returns the absolute path of the currently running telagui binary.
func selfExePath() string {
	exe, err := os.Executable()
	if err != nil {
		return ""
	}
	exe, _ = filepath.Abs(exe)
	return exe
}

// selfUpdatePath returns the staging path for a pending update (next to the running binary).
func selfUpdatePath() string {
	exe := selfExePath()
	if exe == "" {
		return ""
	}
	ext := filepath.Ext(exe)
	base := strings.TrimSuffix(exe, ext)
	return base + "-update" + ext
}

// applyPendingSelfUpdate checks for a staged update binary and swaps it in place.
func (a *App) applyPendingSelfUpdate() {
	updatePath := selfUpdatePath()
	if updatePath == "" {
		return
	}
	if _, err := os.Stat(updatePath); err != nil {
		return // no pending update
	}

	currentPath := selfExePath()
	if currentPath == "" {
		return
	}

	if runtime.GOOS == "windows" {
		// Can't overwrite running exe -- rename current to .old first
		oldPath := currentPath + ".old"
		os.Remove(oldPath)
		if err := os.Rename(currentPath, oldPath); err != nil {
			log.Printf("[update] failed to rename current binary: %v", err)
			return
		}
		if err := os.Rename(updatePath, currentPath); err != nil {
			// Rollback
			os.Rename(oldPath, currentPath)
			log.Printf("[update] failed to install update: %v", err)
			return
		}
		// Clean up old binary (may fail if still locked, that's ok)
		go func() {
			time.Sleep(2 * time.Second)
			os.Remove(oldPath)
		}()
	} else {
		// Unix: just rename over the running binary
		if err := os.Rename(updatePath, currentPath); err != nil {
			log.Printf("[update] failed to install update: %v", err)
			return
		}
		os.Chmod(currentPath, 0755)
	}

	log.Printf("[update] applied pending update")
}


// GetVersion returns the current telagui version.
func (a *App) GetVersion() string {
	return version
}

// ToolVersions contains version info for all managed binaries.
type ToolVersions struct {
	GUI       string `json:"gui"`
	CLI       string `json:"cli"`
	Latest    string `json:"latest"`
	GUIBehind bool   `json:"guiBehind"`
	CLIBehind bool   `json:"cliBehind"`
}

// GetToolVersions returns versions of all binaries and whether they're behind.
func (a *App) GetToolVersions() ToolVersions {
	tv := ToolVersions{GUI: version}

	// Get CLI version
	bin := "tela"
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	localPath := filepath.Join(telaInstallDir(), bin)
	if _, err := os.Stat(localPath); err == nil {
		cmd := exec.Command(localPath, "version")
		hideConsoleWindow(cmd)
		out, err := cmd.CombinedOutput()
		if err == nil {
			parts := strings.Fields(strings.TrimSpace(string(out)))
			if len(parts) >= 2 {
				tv.CLI = parts[1]
			}
		}
	} else {
		tv.CLI = "not installed"
	}

	// Get latest from cache
	a.mu.Lock()
	tv.Latest = a.updateVersion
	a.mu.Unlock()

	if tv.Latest == "" {
		// Try fetching (may already be cached from checkForUpdates)
		if latest, err := a.latestRelease(); err == nil {
			tv.Latest = latest
		}
	}

	if tv.Latest != "" {
		tv.GUIBehind = tv.GUI != tv.Latest
		tv.CLIBehind = tv.CLI != tv.Latest && tv.CLI != "not installed"
	}

	return tv
}

// CheckForUpdatesNow re-checks for updates (called by Refresh button).
func (a *App) CheckForUpdatesNow() {
	a.checkForUpdates()
}

// HasUpdate returns true if a self-update is pending.
func (a *App) HasUpdate() bool {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.updatePending
}

// IsPackageManaged returns true if installed via a package manager.
func (a *App) IsPackageManaged() bool {
	return isPackageManaged()
}

// GetUpdateVersion returns the version of the pending update.
func (a *App) GetUpdateVersion() string {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.updateVersion
}

// RestartToUpdate downloads updates for all binaries and relaunches.
func (a *App) RestartToUpdate() error {
	a.mu.Lock()
	ver := a.updateVersion
	a.mu.Unlock()

	if ver == "" {
		return fmt.Errorf("no update available")
	}

	// Disconnect if connected and wait for clean shutdown
	a.Disconnect()
	// Give tela a moment to fully exit and release ports
	time.Sleep(1 * time.Second)

	// Update tela CLI
	a.logCommand("Update tela to "+ver, "# downloading tela "+ver)
	a.installTool("tela", ver)

	if isPackageManaged() {
		// Package-managed: CLI updated, GUI must be updated via package manager
		a.mu.Lock()
		a.updatePending = false
		a.mu.Unlock()
		a.logCommand("CLI updated to "+ver, "# GUI update available via your package manager")
		return nil
	}

	// Download telagui update to staging path (next to running binary)
	a.logCommand("Update telagui to "+ver, "# downloading telagui "+ver)
	a.downloadSelfUpdate(ver)

	exe := selfExePath()
	if exe == "" {
		return fmt.Errorf("cannot determine executable path")
	}

	// Apply the update now before relaunching.
	a.applyPendingSelfUpdate()

	// Relaunch from the same path (which is now the new binary)
	cmd := exec.Command(exe)
	cmd.Start()

	os.Exit(0)
	return nil // unreachable
}

// downloadSelfUpdate downloads the telagui binary for the current platform.
func (a *App) downloadSelfUpdate(ver string) {
	ext := ""
	if runtime.GOOS == "windows" {
		ext = ".exe"
	}
	binaryName := fmt.Sprintf("telagui-%s-%s%s", runtime.GOOS, runtime.GOARCH, ext)
	url := fmt.Sprintf("https://github.com/paulmooreparks/tela/releases/download/%s/%s", ver, binaryName)

	os.MkdirAll(telaInstallDir(), 0755)
	updatePath := selfUpdatePath()

	resp, err := http.Get(url)
	if err != nil || resp.StatusCode != 200 {
		if resp != nil {
			resp.Body.Close()
		}
		return
	}
	defer resp.Body.Close()

	tmpPath := updatePath + ".tmp"
	f, err := os.Create(tmpPath)
	if err != nil {
		return
	}
	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		os.Remove(tmpPath)
		return
	}
	f.Close()

	os.Remove(updatePath)
	os.Rename(tmpPath, updatePath)

	if runtime.GOOS != "windows" {
		os.Chmod(updatePath, 0755)
	}
}

func (a *App) shutdown(ctx context.Context) {
	a.mu.Lock()
	if a.telaProcess != nil {
		killProcessTree(a.telaProcess.Pid)
		a.telaProcess = nil
		a.connected = false
	}
	a.mu.Unlock()

	// Force exit after 2 seconds if goroutines are stuck
	go func() {
		time.Sleep(2 * time.Second)
		os.Exit(0)
	}()
}

// --- Window Management ---

// ShouldAutoConnect returns true if auto-connect is enabled and there's a saved profile.
func (a *App) ShouldAutoConnect() bool {
	settings := a.GetSettings()
	if !settings.AutoConnect {
		return false
	}
	// Check if there's a saved profile with connections
	connections := a.LoadProfile()
	return len(connections) > 0
}

// ShowWindow brings the window back from the system tray.
func (a *App) ShowWindow() {
	wailsRuntime.WindowShow(a.ctx)
	wailsRuntime.WindowSetAlwaysOnTop(a.ctx, true)
	wailsRuntime.WindowSetAlwaysOnTop(a.ctx, false)
}

// QuitApp exits the application (used from tray menu).
func (a *App) QuitApp() {
	a.Disconnect()
	// Force exit after a short delay -- Wails Quit may not work
	// if called from a systray goroutine
	go func() {
		time.Sleep(500 * time.Millisecond)
		os.Exit(0)
	}()
	wailsRuntime.Quit(a.ctx)
}

// --- Command Log ---

// GetCommandLog returns all command log entries.
func (a *App) GetCommandLog() []CommandLogEntry {
	a.mu.Lock()
	defer a.mu.Unlock()
	result := make([]CommandLogEntry, len(a.cmdLog))
	copy(result, a.cmdLog)
	return result
}

func (a *App) logCommand(description, command string) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.cmdLog = append(a.cmdLog, CommandLogEntry{
		Time:        time.Now().Format("2006-01-02 15:04:05"),
		Description: description,
		Command:     command,
	})
}

// --- Local Registry ---

func telaConfigDir() string {
	if runtime.GOOS == "windows" {
		if appData := os.Getenv("APPDATA"); appData != "" {
			return filepath.Join(appData, "tela")
		}
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tela")
}

func profilesDir() string {
	return filepath.Join(telaConfigDir(), "profiles")
}

func profilePath() string {
	return filepath.Join(profilesDir(), "telagui.yaml")
}

// GetKnownHubs returns all hubs the user has configured locally.
// Reads from credentials.yaml and hubs.yaml.
func (a *App) GetKnownHubs() []KnownHub {
	seen := make(map[string]bool)
	var hubs []KnownHub

	// 1. Credential store -- hubs with stored tokens
	store, err := credstore.Load(credstore.UserPath())
	if err == nil && store != nil {
		for url, cred := range store.Hubs {
			name := hubNameFromURL(url)
			hubs = append(hubs, KnownHub{
				Name:     name,
				URL:      url,
				HasToken: cred.Token != "",
				Source:   "credentials",
			})
			seen[url] = true
		}
	}

	// 2. Hub aliases -- short names mapped to URLs
	hubsFile := filepath.Join(telaConfigDir(), "hubs.yaml")
	if data, err := os.ReadFile(hubsFile); err == nil {
		var cfg struct {
			Hubs map[string]string `yaml:"hubs"`
		}
		if yaml.Unmarshal(data, &cfg) == nil {
			for name, url := range cfg.Hubs {
				if !seen[url] {
					hasToken := false
					if store != nil {
						_, hasToken = store.Hubs[url]
					}
					hubs = append(hubs, KnownHub{
						Name:     name,
						URL:      url,
						HasToken: hasToken,
						Source:   "hubs",
					})
					seen[url] = true
				}
			}
		}
	}

	return hubs
}

func hubNameFromURL(url string) string {
	url = strings.TrimPrefix(url, "wss://")
	url = strings.TrimPrefix(url, "ws://")
	url = strings.TrimPrefix(url, "https://")
	url = strings.TrimPrefix(url, "http://")
	url = strings.TrimSuffix(url, "/")
	return url
}

// GetHubStatus queries a hub for its machine/service status.
func (a *App) GetHubStatus(hubURL string) HubStatus {
	token := credstore.LookupToken(hubURL)
	if token == "" {
		return HubStatus{Error: "no token stored for this hub"}
	}

	// Convert wss:// to https:// for the API call
	apiURL := hubURL
	apiURL = strings.Replace(apiURL, "wss://", "https://", 1)
	apiURL = strings.Replace(apiURL, "ws://", "http://", 1)
	apiURL = strings.TrimSuffix(apiURL, "/") + "/api/status"

	req, err := http.NewRequest("GET", apiURL, nil)
	if err != nil {
		return HubStatus{Error: err.Error()}
	}
	req.Header.Set("Authorization", "Bearer "+token)

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return HubStatus{Error: err.Error()}
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return HubStatus{Error: fmt.Sprintf("HTTP %d", resp.StatusCode)}
	}

	var raw struct {
		HubName  string `json:"hubName"`
		Machines []struct {
			ID             string `json:"id"`
			Hostname       string `json:"hostname"`
			OS             string `json:"os"`
			AgentConnected bool   `json:"agentConnected"`
			SessionCount   int    `json:"sessionCount"`
			LastSeen       string `json:"lastSeen"`
			Services       []struct {
				Name  string `json:"name"`
				Port  int    `json:"port"`
				Proto string `json:"proto"`
			} `json:"services"`
		} `json:"machines"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&raw); err != nil {
		return HubStatus{Error: err.Error()}
	}

	status := HubStatus{
		Online:  true,
		HubName: raw.HubName,
	}
	for _, m := range raw.Machines {
		ms := MachineStatus{
			ID:             m.ID,
			Hostname:       m.Hostname,
			OS:             m.OS,
			AgentConnected: m.AgentConnected,
			SessionCount:   m.SessionCount,
			LastSeen:       m.LastSeen,
		}
		for _, s := range m.Services {
			ms.Services = append(ms.Services, ServiceInfo{
				Name:  s.Name,
				Port:  s.Port,
				Proto: s.Proto,
			})
		}
		status.Machines = append(status.Machines, ms)
	}
	return status
}

// --- Hub Management ---

// AddHub stores a hub URL and token in the credential store.
func (a *App) AddHub(url, token string) error {
	wsURL := toWSURL(url)
	a.logCommand("Add hub "+wsURL, "tela login "+wsURL)

	store, err := credstore.Load(credstore.UserPath())
	if err != nil {
		store = &credstore.Store{Hubs: make(map[string]credstore.Credential)}
	}
	store.Set(wsURL, credstore.Credential{Token: token})
	return store.Save(credstore.UserPath())
}

// RemoveHub removes a hub from the credential store.
func (a *App) RemoveHub(url string) error {
	wsURL := toWSURL(url)
	a.logCommand("Remove hub "+wsURL, "tela logout "+wsURL)

	// Remove from credential store
	store, err := credstore.Load(credstore.UserPath())
	if err == nil {
		store.Remove(wsURL)
		store.Save(credstore.UserPath())
	}

	// Remove from hubs.yaml aliases
	hubsFile := filepath.Join(telaConfigDir(), "hubs.yaml")
	if data, err := os.ReadFile(hubsFile); err == nil {
		var cfg struct {
			Hubs map[string]string `yaml:"hubs"`
		}
		if yaml.Unmarshal(data, &cfg) == nil && cfg.Hubs != nil {
			changed := false
			for name, hubURL := range cfg.Hubs {
				if hubURL == url || hubURL == wsURL {
					delete(cfg.Hubs, name)
					changed = true
				}
			}
			if changed {
				out, _ := yaml.Marshal(&cfg)
				os.WriteFile(hubsFile, out, 0600)
			}
		}
	}

	return nil
}

// GetStoredToken checks the credential store for a token for the given hub URL.
func (a *App) GetStoredToken(hubURL string) string {
	return credstore.LookupToken(toWSURL(hubURL))
}

// --- Docker Integration ---

// DockerGetToken runs telahubd user show-owner inside a Docker container.
func (a *App) DockerGetToken(container, role string) (string, error) {
	if role == "" {
		role = "show-owner"
	}
	cmd := fmt.Sprintf("docker exec %s telahubd user %s -config /app/data/telahubd.yaml",
		container, role)
	a.logCommand("Get "+role+" token from container "+container, cmd)

	out, err := exec.Command("docker", "exec", container,
		"telahubd", "user", role, "-config", "/app/data/telahubd.yaml").CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s: %s", err, strings.TrimSpace(string(out)))
	}
	return strings.TrimSpace(string(out)), nil
}

// DockerListContainers lists running Docker containers (for hub discovery).
func (a *App) DockerListContainers() ([]string, error) {
	out, err := exec.Command("docker", "ps", "--format", "{{.Names}}").CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("docker not available: %s", strings.TrimSpace(string(out)))
	}
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	var names []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" {
			names = append(names, line)
		}
	}
	return names, nil
}

// --- Profile-Based Connection ---

// AssignLocalPort picks a unique local port for a service. Checks system
// availability AND avoids ports already assigned to other selected services.
func (a *App) AssignLocalPort(servicePort int) int {
	a.mu.Lock()
	defer a.mu.Unlock()

	// Try the advertised port first
	if !a.assignedPorts[servicePort] && isPortAvailable(servicePort) {
		a.assignedPorts[servicePort] = true
		return servicePort
	}

	// Try port + 10000, then increment until we find one
	candidate := servicePort + 10000
	for i := 0; i < 100; i++ {
		if !a.assignedPorts[candidate] && isPortAvailable(candidate) {
			a.assignedPorts[candidate] = true
			return candidate
		}
		candidate++
	}

	// Last resort
	a.assignedPorts[servicePort] = true
	return servicePort
}

// PortRequest is a service that needs a local port assigned.
type PortRequest struct {
	Key         string `json:"key"`         // unique key like "hub||machine||service"
	ServicePort int    `json:"servicePort"` // the advertised remote port
}

// PortAssignment is the result of port resolution.
type PortAssignment struct {
	Key       string `json:"key"`
	LocalPort int    `json:"localPort"`
}

// ResolveAllPorts takes all selected services and assigns clash-free local ports.
// Called whenever selections change. Resets all previous assignments.
func (a *App) ResolveAllPorts(requestsJSON string) ([]PortAssignment, error) {
	var requests []PortRequest
	if err := json.Unmarshal([]byte(requestsJSON), &requests); err != nil {
		return nil, fmt.Errorf("invalid requests: %w", err)
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	// Reset all assignments
	a.assignedPorts = make(map[int]bool)

	var results []PortAssignment
	for _, req := range requests {
		port := req.ServicePort

		// Try the advertised port
		if !a.assignedPorts[port] && isPortAvailable(port) {
			a.assignedPorts[port] = true
			results = append(results, PortAssignment{Key: req.Key, LocalPort: port})
			continue
		}

		// Try port + 10000, then increment
		candidate := port + 10000
		found := false
		for i := 0; i < 100; i++ {
			if !a.assignedPorts[candidate] && isPortAvailable(candidate) {
				a.assignedPorts[candidate] = true
				results = append(results, PortAssignment{Key: req.Key, LocalPort: candidate})
				found = true
				break
			}
			candidate++
		}
		if !found {
			// Last resort -- use the original port
			a.assignedPorts[port] = true
			results = append(results, PortAssignment{Key: req.Key, LocalPort: port})
		}
	}

	return results, nil
}

// ReleaseLocalPort frees a previously assigned port.
func (a *App) ReleaseLocalPort(port int) {
	a.mu.Lock()
	defer a.mu.Unlock()
	delete(a.assignedPorts, port)
}

func isPortAvailable(port int) bool {
	// Check both loopback and all interfaces (Docker binds on 0.0.0.0)
	for _, addr := range []string{"127.0.0.1", "0.0.0.0"} {
		ln, err := net.Listen("tcp", fmt.Sprintf("%s:%d", addr, port))
		if err != nil {
			return false
		}
		ln.Close()
	}
	return true
}

// LoadProfile reads the saved profile and returns its connections.
func (a *App) LoadProfile() []ProfileConnection {
	data, err := os.ReadFile(profilePath())
	if err != nil {
		return nil
	}
	var profile Profile
	if err := yaml.Unmarshal(data, &profile); err != nil {
		return nil
	}
	return profile.Connections
}

// SaveProfile writes the profile YAML and returns its path.
func (a *App) SaveProfile(connectionsJSON string) (string, error) {
	var connections []ProfileConnection
	if err := json.Unmarshal([]byte(connectionsJSON), &connections); err != nil {
		return "", fmt.Errorf("invalid connections: %w", err)
	}

	// Resolve tokens from credential store for each connection.
	// Tokens are written directly into the profile (file is 0600).
	for i := range connections {
		if connections[i].Token == "" || connections[i].Token == "${TELA_TOKEN}" {
			token := credstore.LookupToken(connections[i].Hub)
			if token != "" {
				connections[i].Token = token
			}
		}
	}

	profile := Profile{Connections: connections}

	data, err := yaml.Marshal(profile)
	if err != nil {
		return "", fmt.Errorf("marshal profile: %w", err)
	}

	dir := profilesDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return "", fmt.Errorf("create profiles dir: %w", err)
	}

	path := profilePath()
	if err := os.WriteFile(path, data, 0600); err != nil {
		return "", fmt.Errorf("write profile: %w", err)
	}

	a.logCommand("Save profile", "cat "+path)
	return path, nil
}

// Connect starts tela connect -profile telagui in the background.
func (a *App) Connect(connectionsJSON string) (string, error) {
	a.mu.Lock()
	if a.connected {
		a.mu.Unlock()
		return "", fmt.Errorf("already connected -- disconnect first")
	}
	a.mu.Unlock()

	telaPath := a.findTool("tela")
	if telaPath == "" {
		// Auto-download from GitHub
		var err error
		telaPath, err = a.EnsureTool("tela")
		if err != nil {
			return "", fmt.Errorf("tela not available and download failed: %w", err)
		}
	}

	path, err := a.SaveProfile(connectionsJSON)
	if err != nil {
		return "", err
	}

	cmdStr := "tela connect -profile " + path
	a.logCommand("Connect using profile", cmdStr)

	cmd := exec.Command(telaPath, "connect", "-profile", path)
	hideConsoleWindow(cmd)

	outPipe, _ := cmd.StdoutPipe()
	cmd.Stderr = cmd.Stdout

	if err := cmd.Start(); err != nil {
		return "", fmt.Errorf("failed to start tela: %w", err)
	}

	pid := cmd.Process.Pid

	a.mu.Lock()
	a.telaProcess = cmd.Process
	a.connected = true
	a.telaOutput = ""
	a.mu.Unlock()

	go func() {
		buf := make([]byte, 4096)
		for {
			n, err := outPipe.Read(buf)
			if n > 0 {
				a.mu.Lock()
				a.telaOutput += string(buf[:n])
				a.mu.Unlock()
			}
			if err != nil {
				break
			}
		}
		cmd.Wait()
		a.mu.Lock()
		a.connected = false
		a.mu.Unlock()
	}()

	return fmt.Sprintf("Connected (pid %d)", pid), nil
}

// Disconnect kills the running tela process.
func (a *App) Disconnect() error {
	// Try the control API first (graceful shutdown)
	if a.disconnectViaControlAPI() {
		a.logCommand("Disconnect", "curl -X DELETE http://localhost:<port>/ -H 'Authorization: Bearer <token>'")
		a.mu.Lock()
		a.telaProcess = nil
		a.connected = false
		a.mu.Unlock()
		return nil
	}

	// Fallback: kill the process directly
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.telaProcess != nil {
		pid := a.telaProcess.Pid
		killProcessTree(pid)
		a.telaProcess.Kill()
		a.telaProcess = nil
		a.connected = false
		a.logCommand("Disconnect (forced)", fmt.Sprintf("taskkill /PID %d /T /F", pid))
		return nil
	}
	a.connected = false
	return nil
}

// disconnectViaControlAPI reads the control file and sends DELETE / to the tela control API.
func (a *App) disconnectViaControlAPI() bool {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return false
	}

	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 || info.Token == "" {
		return false
	}

	url := fmt.Sprintf("http://127.0.0.1:%d/", info.Port)
	req, err := http.NewRequest("DELETE", url, nil)
	if err != nil {
		return false
	}
	req.Header.Set("Authorization", "Bearer "+info.Token)

	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return false
	}
	defer resp.Body.Close()

	// Wait for the process to exit
	a.mu.Lock()
	proc := a.telaProcess
	a.mu.Unlock()
	if proc != nil {
		// Give it up to 5 seconds to exit gracefully
		done := make(chan struct{})
		go func() {
			proc.Wait()
			close(done)
		}()
		select {
		case <-done:
		case <-time.After(5 * time.Second):
			// Force kill if it doesn't exit
			killProcessTree(proc.Pid)
		}
	}

	return resp.StatusCode == 202
}

// GetConnectionState returns the current connection state.
func (a *App) GetConnectionState() ConnectionState {
	a.mu.Lock()
	defer a.mu.Unlock()

	state := ConnectionState{
		Connected: a.connected,
		Output:    a.telaOutput,
	}

	if a.telaProcess != nil {
		state.Pid = a.telaProcess.Pid
	}

	// Load the saved profile to show connection details
	if a.connected {
		data, err := os.ReadFile(profilePath())
		if err == nil {
			var profile Profile
			if yaml.Unmarshal(data, &profile) == nil {
				state.Connections = profile.Connections
			}
		}
	}

	return state
}

// SetVerbose toggles verbose logging on the running tela instance via control API.
func (a *App) SetVerbose(on bool) error {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return fmt.Errorf("not connected")
	}
	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 {
		return fmt.Errorf("invalid control file")
	}

	req, _ := http.NewRequest("PUT", fmt.Sprintf("http://127.0.0.1:%d/verbose", info.Port), nil)
	req.Header.Set("Authorization", "Bearer "+info.Token)

	client := &http.Client{Timeout: 3 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("control API unreachable: %w", err)
	}
	resp.Body.Close()

	state := "off"
	if on {
		state = "on"
	}
	a.logCommand("Set verbose "+state, "# toggled via control API PUT /verbose")
	return nil
}

// SaveTerminalOutput saves the terminal output using a save dialog.
func (a *App) SaveTerminalOutput(content string) (string, error) {
	filename := fmt.Sprintf("tela-%s.log", time.Now().Format("2006-01-02-150405"))

	dialog, err := wailsRuntime.SaveFileDialog(a.ctx, wailsRuntime.SaveDialogOptions{
		DefaultFilename: filename,
		Title:           "Save Terminal Output",
		Filters: []wailsRuntime.FileFilter{
			{DisplayName: "Log Files", Pattern: "*.log"},
			{DisplayName: "Text Files", Pattern: "*.txt"},
			{DisplayName: "All Files", Pattern: "*.*"},
		},
	})
	if err != nil {
		return "", fmt.Errorf("dialog failed: %w", err)
	}
	if dialog == "" {
		return "", nil // user cancelled
	}

	if err := os.WriteFile(dialog, []byte(content), 0600); err != nil {
		return "", fmt.Errorf("save failed: %w", err)
	}
	a.logCommand("Save terminal output", "# saved to "+dialog)
	return dialog, nil
}

// PairWithCode exchanges a pairing code for a connect token via the tela CLI.
func (a *App) PairWithCode(hubURL, code string) error {
	telaPath := a.findTool("tela")
	if telaPath == "" {
		// Try to download
		var err error
		telaPath, err = a.EnsureTool("tela")
		if err != nil {
			return fmt.Errorf("tela not available: %w", err)
		}
	}

	wsURL := toWSURL(hubURL)
	cmdStr := "tela pair -hub " + wsURL + " -code " + code
	a.logCommand("Pair with hub "+wsURL, cmdStr)

	cmd := exec.Command(telaPath, "pair", "-hub", wsURL, "-code", code)
	hideConsoleWindow(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		output := strings.TrimSpace(string(out))
		if output != "" {
			return fmt.Errorf("%s", output)
		}
		return fmt.Errorf("pairing failed: %w", err)
	}

	return nil
}

// DetectCredentialType returns "code" if the input looks like a pairing code,
// "token" if it looks like a hex token, or "unknown".
func (a *App) DetectCredentialType(input string) string {
	input = strings.TrimSpace(input)
	// Pairing code: 4-4 alphanumeric with dash (e.g., ABCD-1234)
	if len(input) == 9 && input[4] == '-' {
		return "code"
	}
	// Hex token: 64 hex characters
	if len(input) == 64 {
		allHex := true
		for _, c := range input {
			if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
				allHex = false
				break
			}
		}
		if allHex {
			return "token"
		}
	}
	return "unknown"
}

// GetControlStatus reads live status from the tela control API.
func (a *App) GetControlStatus() map[string]interface{} {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return nil
	}

	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 {
		return nil
	}

	req, _ := http.NewRequest("GET", fmt.Sprintf("http://127.0.0.1:%d/", info.Port), nil)
	req.Header.Set("Authorization", "Bearer "+info.Token)

	client := &http.Client{Timeout: 3 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	return result
}

// --- Tool Management ---

func (a *App) findTool(name string) string {
	bin := name
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	// Always use the GUI's own managed copy
	local := filepath.Join(telaInstallDir(), bin)
	if _, err := os.Stat(local); err == nil {
		return local
	}
	return ""
}

func telaInstallDir() string {
	if runtime.GOOS == "windows" {
		return filepath.Join(os.Getenv("LOCALAPPDATA"), "Tela", "bin")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tela", "bin")
}

// EnsureTool checks if a tool is installed, downloads it if not.
func (a *App) EnsureTool(name string) (string, error) {
	path := a.findTool(name)
	if path != "" {
		return path, nil
	}

	version, err := a.latestRelease()
	if err != nil {
		return "", fmt.Errorf("cannot determine latest version: %w", err)
	}

	return a.installTool(name, version)
}

func (a *App) latestRelease() (string, error) {
	req, _ := http.NewRequest("GET", "https://api.github.com/repos/paulmooreparks/tela/releases/latest", nil)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	resp, err := a.httpClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	var release struct {
		TagName string `json:"tag_name"`
	}
	json.NewDecoder(resp.Body).Decode(&release)
	return release.TagName, nil
}

func (a *App) installTool(name, version string) (string, error) {
	ext := ""
	if runtime.GOOS == "windows" {
		ext = ".exe"
	}
	url := fmt.Sprintf("https://github.com/paulmooreparks/tela/releases/download/%s/%s-%s-%s%s",
		version, name, runtime.GOOS, runtime.GOARCH, ext)

	installDir := telaInstallDir()
	os.MkdirAll(installDir, 0755)
	destPath := filepath.Join(installDir, name+ext)

	a.logCommand("Install "+name+" "+version,
		fmt.Sprintf("curl -fSL -o %q %s", destPath, url))

	resp, err := http.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("download failed: HTTP %d", resp.StatusCode)
	}

	// Atomic write: download to temp file, then rename
	tmpPath := destPath + ".tmp"
	f, err := os.Create(tmpPath)
	if err != nil {
		return "", err
	}
	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		os.Remove(tmpPath)
		return "", fmt.Errorf("download incomplete: %w", err)
	}
	f.Close()

	// Replace existing binary atomically
	os.Remove(destPath) // Windows requires removing before rename
	if err := os.Rename(tmpPath, destPath); err != nil {
		os.Remove(tmpPath)
		return "", fmt.Errorf("install failed: %w", err)
	}

	if runtime.GOOS != "windows" {
		os.Chmod(destPath, 0755)
	}
	return destPath, nil
}

// --- Settings ---

// Settings holds user preferences persisted to disk.
type Settings struct {
	AutoConnect     bool `yaml:"autoConnect" json:"autoConnect"`
	ReconnectOnDrop bool `yaml:"reconnectOnDrop" json:"reconnectOnDrop"`
	MinimizeToTray  bool `yaml:"minimizeToTray" json:"minimizeToTray"`
	StartMinimized  bool `yaml:"startMinimized" json:"startMinimized"`
	AutoCheckUpdates bool `yaml:"autoCheckUpdates" json:"autoCheckUpdates"`
	VerboseDefault  bool `yaml:"verboseDefault" json:"verboseDefault"`
}

func defaultSettings() Settings {
	return Settings{
		AutoConnect:      false,
		ReconnectOnDrop:  true,
		MinimizeToTray:   false,
		StartMinimized:   false,
		AutoCheckUpdates: true,
		VerboseDefault:   false,
	}
}

func settingsPath() string {
	return filepath.Join(telaConfigDir(), "telagui-settings.yaml")
}

// GetSettings loads settings from disk, returning defaults if not found.
func (a *App) GetSettings() Settings {
	data, err := os.ReadFile(settingsPath())
	if err != nil {
		return defaultSettings()
	}
	s := defaultSettings()
	if err := yaml.Unmarshal(data, &s); err != nil {
		return defaultSettings()
	}
	return s
}

// SaveSettings persists settings to disk.
func (a *App) SaveSettings(jsonStr string) error {
	var s Settings
	if err := json.Unmarshal([]byte(jsonStr), &s); err != nil {
		return fmt.Errorf("invalid settings: %w", err)
	}

	data, err := yaml.Marshal(&s)
	if err != nil {
		return fmt.Errorf("marshal settings: %w", err)
	}

	dir := telaConfigDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	if err := os.WriteFile(settingsPath(), data, 0600); err != nil {
		return fmt.Errorf("write settings: %w", err)
	}

	a.logCommand("Save settings", "# saved to "+settingsPath())
	return nil
}

// GetCLIPath returns the path to the tela CLI binary.
func (a *App) GetCLIPath() string {
	path := a.findTool("tela")
	if path == "" {
		return "not installed"
	}
	return path
}

// ClearCredentialStore deletes the credential store file.
func (a *App) ClearCredentialStore() error {
	credPath := credstore.UserPath()
	if _, err := os.Stat(credPath); os.IsNotExist(err) {
		return nil
	}
	if err := os.Remove(credPath); err != nil {
		return fmt.Errorf("remove credential store: %w", err)
	}
	a.logCommand("Clear credential store", "rm "+credPath)
	return nil
}

// ImportProfile opens a file dialog and reads a profile YAML, replacing the current profile.
func (a *App) ImportProfile() error {
	dialog, err := wailsRuntime.OpenFileDialog(a.ctx, wailsRuntime.OpenDialogOptions{
		Title: "Import Profile",
		Filters: []wailsRuntime.FileFilter{
			{DisplayName: "YAML Files", Pattern: "*.yaml;*.yml"},
			{DisplayName: "All Files", Pattern: "*.*"},
		},
	})
	if err != nil {
		return fmt.Errorf("dialog failed: %w", err)
	}
	if dialog == "" {
		return nil // user cancelled
	}

	data, err := os.ReadFile(dialog)
	if err != nil {
		return fmt.Errorf("read profile: %w", err)
	}

	// Validate that it parses as a profile
	var profile Profile
	if err := yaml.Unmarshal(data, &profile); err != nil {
		return fmt.Errorf("invalid profile YAML: %w", err)
	}

	dir := profilesDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create profiles dir: %w", err)
	}

	if err := os.WriteFile(profilePath(), data, 0600); err != nil {
		return fmt.Errorf("write profile: %w", err)
	}

	a.logCommand("Import profile", "# imported from "+dialog)
	return nil
}

// ExportProfile opens a save dialog and writes the current profile YAML.
func (a *App) ExportProfile() error {
	data, err := os.ReadFile(profilePath())
	if err != nil {
		return fmt.Errorf("no profile to export: %w", err)
	}

	dialog, err := wailsRuntime.SaveFileDialog(a.ctx, wailsRuntime.SaveDialogOptions{
		DefaultFilename: "telagui-profile.yaml",
		Title:           "Export Profile",
		Filters: []wailsRuntime.FileFilter{
			{DisplayName: "YAML Files", Pattern: "*.yaml;*.yml"},
			{DisplayName: "All Files", Pattern: "*.*"},
		},
	})
	if err != nil {
		return fmt.Errorf("dialog failed: %w", err)
	}
	if dialog == "" {
		return nil // user cancelled
	}

	if err := os.WriteFile(dialog, data, 0600); err != nil {
		return fmt.Errorf("save profile: %w", err)
	}

	a.logCommand("Export profile", "# exported to "+dialog)
	return nil
}

// --- Helpers ---

func toWSURL(hubURL string) string {
	if strings.HasPrefix(hubURL, "https://") {
		return "wss://" + strings.TrimPrefix(hubURL, "https://")
	}
	if strings.HasPrefix(hubURL, "http://") {
		return "ws://" + strings.TrimPrefix(hubURL, "http://")
	}
	if !strings.HasPrefix(hubURL, "wss://") && !strings.HasPrefix(hubURL, "ws://") {
		return "wss://" + hubURL
	}
	return hubURL
}
