package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/cookiejar"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/paulmooreparks/tela/internal/credstore"
	"gopkg.in/yaml.v3"
)

// PortalConnection represents a connected portal.
type PortalConnection struct {
	URL         string `json:"url" yaml:"url"`
	DisplayName string `json:"displayName" yaml:"display_name"`
	Email       string `json:"email" yaml:"email"`
	Connected   bool   `json:"connected" yaml:"-"`
}

// SavedPortals is the on-disk format for portal connections.
type SavedPortals struct {
	Portals []PortalConnection `yaml:"portals"`
}

// App is the main application struct exposed to the frontend via Wails bindings.
type App struct {
	ctx context.Context

	mu          sync.Mutex
	cmdLog      []CommandLogEntry
	portals     []PortalConnection
	httpClient  *http.Client
	connections []ActiveConnection
}

// CommandLogEntry records a CLI command generated by the GUI.
type CommandLogEntry struct {
	Time        string `json:"time"`
	Description string `json:"description"`
	Command     string `json:"command"`
}

// NewApp creates a new App instance.
func NewApp() *App {
	jar, _ := cookiejar.New(nil)
	return &App{
		httpClient: &http.Client{
			Timeout: 30 * time.Second,
			Jar:     jar,
		},
	}
}

func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
	// Load saved portals and reconnect
	a.loadSavedPortals()
}

func (a *App) shutdown(ctx context.Context) {
	// Kill all child tela processes
	a.mu.Lock()
	for _, conn := range a.connections {
		if conn.Running && conn.process != nil {
			conn.process.Kill()
		}
	}
	a.mu.Unlock()
}

func portalsConfigPath() string {
	return filepath.Join(credstore.UserDir(), "portals.yaml")
}

func (a *App) loadSavedPortals() {
	data, err := os.ReadFile(portalsConfigPath())
	if err != nil {
		return
	}
	var saved SavedPortals
	if err := yaml.Unmarshal(data, &saved); err != nil {
		return
	}
	a.mu.Lock()
	a.portals = saved.Portals
	a.mu.Unlock()
}

func (a *App) savePortals() error {
	a.mu.Lock()
	saved := SavedPortals{Portals: a.portals}
	a.mu.Unlock()

	data, err := yaml.Marshal(&saved)
	if err != nil {
		return err
	}
	dir := filepath.Dir(portalsConfigPath())
	os.MkdirAll(dir, 0700)
	return os.WriteFile(portalsConfigPath(), data, 0600)
}

// GetPortals returns all saved portals with their connection status.
func (a *App) GetPortals() []PortalConnection {
	a.mu.Lock()
	defer a.mu.Unlock()
	result := make([]PortalConnection, len(a.portals))
	copy(result, a.portals)
	return result
}

// AddPortal signs in to a portal and saves it.
func (a *App) AddPortal(portalURL, email, password string) (string, error) {
	portalURL = strings.TrimRight(portalURL, "/")
	a.logCommand("Sign in to "+portalURL,
		fmt.Sprintf("tela remote add portal %s", portalURL))

	body := fmt.Sprintf(`{"email":%q,"password":%q}`, email, password)
	resp, err := a.httpClient.Post(portalURL+"/api/login", "application/json", strings.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("connection failed: %w", err)
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)

	if resp.StatusCode != 200 {
		errMsg, _ := result["error"].(string)
		if errMsg == "" {
			errMsg = fmt.Sprintf("HTTP %d", resp.StatusCode)
		}
		return "", fmt.Errorf("%s", errMsg)
	}

	name, _ := result["displayName"].(string)
	if name == "" {
		name = email
	}

	portal := PortalConnection{
		URL:         portalURL,
		DisplayName: name,
		Email:       email,
		Connected:   true,
	}

	a.mu.Lock()
	// Replace existing or add new
	found := false
	for i, p := range a.portals {
		if p.URL == portalURL {
			a.portals[i] = portal
			found = true
			break
		}
	}
	if !found {
		a.portals = append(a.portals, portal)
	}
	a.mu.Unlock()

	a.savePortals()
	return name, nil
}

// RemovePortal removes a saved portal.
func (a *App) RemovePortal(portalURL string) error {
	a.mu.Lock()
	var filtered []PortalConnection
	for _, p := range a.portals {
		if p.URL != portalURL {
			filtered = append(filtered, p)
		}
	}
	a.portals = filtered
	a.mu.Unlock()
	return a.savePortals()
}

// --- Command Log ---

// GetCommandLog returns the full command history.
func (a *App) GetCommandLog() []CommandLogEntry {
	a.mu.Lock()
	defer a.mu.Unlock()
	result := make([]CommandLogEntry, len(a.cmdLog))
	copy(result, a.cmdLog)
	return result
}

func (a *App) logCommand(description, command string) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.cmdLog = append(a.cmdLog, CommandLogEntry{
		Time:        time.Now().Format("2006-01-02 15:04:05"),
		Description: description,
		Command:     command,
	})
}

// --- Tool Management ---

// ToolStatus reports whether a tela binary is installed and its version.
type ToolStatus struct {
	Name      string `json:"name"`
	Installed bool   `json:"installed"`
	Version   string `json:"version"`
	Path      string `json:"path"`
}

// CheckTools reports the install status of tela, telad, and telahubd.
// Checks PATH first, then the app's own install directory.
func (a *App) CheckTools() []ToolStatus {
	tools := []string{"tela", "telad", "telahubd"}
	var results []ToolStatus
	for _, name := range tools {
		bin := name
		if runtime.GOOS == "windows" {
			bin += ".exe"
		}
		// Check PATH first
		found := ""
		p, err := exec.LookPath(bin)
		if err == nil {
			found = p
		}
		// Then check app's own install directory
		if found == "" {
			local := filepath.Join(telaInstallDir(), bin)
			if _, err := os.Stat(local); err == nil {
				found = local
			}
		}
		if found == "" {
			results = append(results, ToolStatus{Name: name, Installed: false})
			continue
		}
		version := ""
		out, err := exec.Command(found, "version").CombinedOutput()
		if err == nil {
			version = strings.TrimSpace(string(out))
		}
		results = append(results, ToolStatus{
			Name:      name,
			Installed: true,
			Version:   version,
			Path:      found,
		})
	}
	return results
}

// LatestRelease returns the latest release tag from GitHub.
func (a *App) LatestRelease() (string, error) {
	req, _ := http.NewRequest("GET", "https://api.github.com/repos/paulmooreparks/tela/releases/latest", nil)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	resp, err := a.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to check releases: %w", err)
	}
	defer resp.Body.Close()
	var release struct {
		TagName string `json:"tag_name"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&release); err != nil {
		return "", fmt.Errorf("failed to parse release: %w", err)
	}
	return release.TagName, nil
}

// InstallTool downloads and installs a tela binary from GitHub releases.
func (a *App) InstallTool(name string, version string) (string, error) {
	osSuffix := runtime.GOOS
	archSuffix := runtime.GOARCH
	ext := ""
	if runtime.GOOS == "windows" {
		ext = ".exe"
	}

	url := fmt.Sprintf("https://github.com/paulmooreparks/tela/releases/download/%s/%s-%s-%s%s",
		version, name, osSuffix, archSuffix, ext)

	installDir := telaInstallDir()
	if err := os.MkdirAll(installDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create install dir: %w", err)
	}
	destPath := filepath.Join(installDir, name+ext)

	a.logCommand("Install "+name+" "+version,
		fmt.Sprintf("curl -fSL -o %q %s", destPath, url))

	dlClient := &http.Client{Timeout: 120 * time.Second}
	resp, err := dlClient.Get(url)
	if err != nil {
		return "", fmt.Errorf("download failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("download failed: HTTP %d", resp.StatusCode)
	}

	f, err := os.Create(destPath)
	if err != nil {
		return "", fmt.Errorf("failed to create file: %w", err)
	}
	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		return "", fmt.Errorf("download failed: %w", err)
	}
	f.Close()

	if runtime.GOOS != "windows" {
		os.Chmod(destPath, 0755)
	}

	return destPath, nil
}

func telaInstallDir() string {
	if runtime.GOOS == "windows" {
		return filepath.Join(os.Getenv("LOCALAPPDATA"), "Tela", "bin")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tela", "bin")
}

// --- Portal Connection ---

// SignIn authenticates with an Awan Saya portal and stores the session.
// SignIn delegates to AddPortal for backward compatibility.
func (a *App) SignIn(portalURL, email, password string) (string, error) {
	return a.AddPortal(portalURL, email, password)
}

// GetOrganizations returns the user's organizations from the portal.
func (a *App) GetOrganizations() ([]map[string]interface{}, error) {
	data, err := a.portalGet("/api/me/organizations")
	if err != nil {
		return nil, err
	}
	orgs, ok := data["organizations"].([]interface{})
	if !ok {
		return nil, fmt.Errorf("unexpected response format")
	}
	var result []map[string]interface{}
	for _, o := range orgs {
		if m, ok := o.(map[string]interface{}); ok {
			result = append(result, m)
		}
	}
	return result, nil
}

// GetOrgHubs returns hubs for an organization.
func (a *App) GetOrgHubs(orgID string) ([]map[string]interface{}, error) {
	data, err := a.portalGet("/api/organizations/" + orgID + "/hubs")
	if err != nil {
		return nil, err
	}
	hubs, ok := data["hubs"].([]interface{})
	if !ok {
		return nil, fmt.Errorf("unexpected response format")
	}
	var result []map[string]interface{}
	for _, h := range hubs {
		if m, ok := h.(map[string]interface{}); ok {
			result = append(result, m)
		}
	}
	return result, nil
}

// GetHubStatus returns machine/service status for a hub.
func (a *App) GetHubStatus(hubName string) (map[string]interface{}, error) {
	return a.portalGet("/api/hub-status/" + hubName)
}

// ActiveConnection tracks a running tela connect process.
type ActiveConnection struct {
	Machine string     `json:"machine"`
	Service string     `json:"service"`
	HubName string     `json:"hubName"`
	Pid     int        `json:"pid"`
	Output  string     `json:"output"`
	Running bool       `json:"running"`
	process *os.Process `json:"-"`
}

// Connect starts a tela connection to a machine service in the background.
func (a *App) Connect(hubURL, machine, service, token string) (string, error) {
	telaPath := a.findTool("tela")
	if telaPath == "" {
		return "", fmt.Errorf("tela not found in PATH or install directory")
	}

	// Build a wss:// URL from the hub's HTTP URL
	wsURL := hubURL
	if strings.HasPrefix(wsURL, "https://") {
		wsURL = "wss://" + strings.TrimPrefix(wsURL, "https://")
	} else if strings.HasPrefix(wsURL, "http://") {
		wsURL = "ws://" + strings.TrimPrefix(wsURL, "http://")
	} else if !strings.HasPrefix(wsURL, "wss://") && !strings.HasPrefix(wsURL, "ws://") {
		wsURL = "wss://" + wsURL
	}

	args := []string{"connect",
		"-hub", wsURL,
		"-machine", machine,
		"-services", service,
	}
	if token != "" {
		args = append(args, "-token", token)
	}

	// Build sanitized command string for the log
	cmdStr := "tela connect -hub " + wsURL + " -machine " + machine + " -services " + service
	if token != "" {
		cmdStr += " -token $TELA_TOKEN"
	}
	a.logCommand("Connect to "+machine+" via "+service, cmdStr)

	cmd := exec.Command(telaPath, args...)

	// Hide console window on Windows
	hideConsoleWindow(cmd)

	// Capture output
	outPipe, _ := cmd.StdoutPipe()
	cmd.Stderr = cmd.Stdout

	if err := cmd.Start(); err != nil {
		return "", fmt.Errorf("failed to start tela: %w", err)
	}

	connID := fmt.Sprintf("%s/%s", machine, service)
	pid := cmd.Process.Pid

	// Read output in background
	go func() {
		buf := make([]byte, 4096)
		for {
			n, err := outPipe.Read(buf)
			if n > 0 {
				a.mu.Lock()
				conn := a.findConnection(connID)
				if conn != nil {
					conn.Output += string(buf[:n])
				}
				a.mu.Unlock()
			}
			if err != nil {
				break
			}
		}
		cmd.Wait()
		a.mu.Lock()
		conn := a.findConnection(connID)
		if conn != nil {
			conn.Running = false
		}
		a.mu.Unlock()
	}()

	// Track the connection
	a.mu.Lock()
	a.connections = append(a.connections, ActiveConnection{
		Machine: machine,
		Service: service,
		HubName: hubURL,
		Pid:     pid,
		Running: true,
		process: cmd.Process,
	})
	a.mu.Unlock()

	return fmt.Sprintf("Connecting to %s/%s (pid %d)", machine, service, pid), nil
}

// GetConnections returns all active/recent connections.
func (a *App) GetConnections() []ActiveConnection {
	a.mu.Lock()
	defer a.mu.Unlock()
	result := make([]ActiveConnection, len(a.connections))
	copy(result, a.connections)
	return result
}

// GetConnectionOutput returns the output for a specific connection.
func (a *App) GetConnectionOutput(machine, service string) string {
	a.mu.Lock()
	defer a.mu.Unlock()
	conn := a.findConnection(machine + "/" + service)
	if conn != nil {
		return conn.Output
	}
	return ""
}

func (a *App) findConnection(id string) *ActiveConnection {
	for i := range a.connections {
		if a.connections[i].Machine+"/"+a.connections[i].Service == id {
			return &a.connections[i]
		}
	}
	return nil
}

// GetStoredToken checks the credential store for a token for the given hub URL.
func (a *App) GetStoredToken(hubURL string) string {
	wsURL := toWSURL(hubURL)
	store, err := credstore.Load(credstore.UserPath())
	if err != nil {
		return ""
	}
	if cred, ok := store.Get(wsURL); ok {
		return cred.Token
	}
	return ""
}

// StoreToken saves a hub token to the credential store.
func (a *App) StoreToken(hubURL, token string) error {
	wsURL := toWSURL(hubURL)
	a.logCommand("Store credentials for "+wsURL,
		fmt.Sprintf("tela login %s", wsURL))

	store, err := credstore.Load(credstore.UserPath())
	if err != nil {
		store = &credstore.Store{}
	}
	store.Set(wsURL, credstore.Credential{Token: token})
	return store.Save(credstore.UserPath())
}

func toWSURL(hubURL string) string {
	if strings.HasPrefix(hubURL, "https://") {
		return "wss://" + strings.TrimPrefix(hubURL, "https://")
	}
	if strings.HasPrefix(hubURL, "http://") {
		return "ws://" + strings.TrimPrefix(hubURL, "http://")
	}
	return hubURL
}

func (a *App) findTool(name string) string {
	bin := name
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	if p, err := exec.LookPath(bin); err == nil {
		return p
	}
	local := filepath.Join(telaInstallDir(), bin)
	if _, err := os.Stat(local); err == nil {
		return local
	}
	return ""
}

func (a *App) portalGet(path string) (map[string]interface{}, error) {
	a.mu.Lock()
	var portalURL string
	for _, p := range a.portals {
		if p.Connected {
			portalURL = p.URL
			break
		}
	}
	a.mu.Unlock()

	if portalURL == "" {
		return nil, fmt.Errorf("not signed in to any portal")
	}
	url := portalURL + path

	resp, err := a.httpClient.Get(url)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)

	if resp.StatusCode != 200 {
		errMsg, _ := result["error"].(string)
		if errMsg == "" {
			errMsg = fmt.Sprintf("HTTP %d", resp.StatusCode)
		}
		return nil, fmt.Errorf("%s", errMsg)
	}
	return result, nil
}
