package main

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"

	"log"

	wailsRuntime "github.com/wailsapp/wails/v2/pkg/runtime"

	"github.com/gorilla/websocket"
	"github.com/paulmooreparks/tela/internal/credstore"
	"gopkg.in/yaml.v3"
)

// version is set at build time via -ldflags "-X main.version=..."
var version = "dev"

// App is the main application struct exposed to the frontend via Wails bindings.
type App struct {
	ctx context.Context

	mu            sync.Mutex
	cmdLog        []CommandLogEntry
	httpClient    *http.Client
	assignedPorts map[int]bool // ports already assigned in this session

	// Profile-based connection state
	telaProcess *os.Process
	telaOutput  string
	connected   bool
	attached    bool // true when attached to external tela (not launched by TV)

	// Self-update state
	updatePending bool
	updateVersion string

	// Window state
	quitting bool

	// WebSocket control connection
	controlWS *websocket.Conn

}

// CommandLogEntry records a CLI command generated by the GUI.
type CommandLogEntry struct {
	Time        string `json:"time"`
	Method      string `json:"method"` // "GET", "POST", "DELETE", "CLI"
	Description string `json:"description"`
	Command     string `json:"command"`
}

// KnownHub is a hub the GUI knows about from the local registry.
type KnownHub struct {
	Name     string `json:"name"`
	URL      string `json:"url"`
	HasToken bool   `json:"hasToken"`
	Source   string `json:"source"` // "credentials", "hubs"
}

// HubStatus is the status of a hub and its machines.
type HubStatus struct {
	Online   bool            `json:"online"`
	HubName  string          `json:"hubName"`
	Machines []MachineStatus `json:"machines"`
	Error    string          `json:"error,omitempty"`
}

// MachineStatus is the status of a machine on a hub.
type MachineStatus struct {
	ID             string        `json:"id"`
	Hostname       string        `json:"hostname"`
	OS             string        `json:"os"`
	AgentConnected bool          `json:"agentConnected"`
	SessionCount   int           `json:"sessionCount"`
	LastSeen       string        `json:"lastSeen"`
	Services       []ServiceInfo `json:"services"`
}

// ServiceInfo describes a service on a machine.
type ServiceInfo struct {
	Name  string `json:"name"`
	Port  int    `json:"port"`
	Proto string `json:"proto"`
}

// ProfileConnection represents one connection entry in the profile YAML.
type ProfileConnection struct {
	Hub      string           `yaml:"hub" json:"hub"`
	Machine  string           `yaml:"machine" json:"machine"`
	Token    string           `yaml:"token,omitempty" json:"token,omitempty"`
	Services []ProfileService `yaml:"services" json:"services"`
}

// ProfileService represents one service in a profile connection.
type ProfileService struct {
	Name   string `yaml:"name" json:"name"`
	Local  int    `yaml:"local" json:"local"`
	Remote int    `yaml:"remote,omitempty" json:"remote,omitempty"`
}

// Profile is the top-level profile YAML structure.
type Profile struct {
	Connections []ProfileConnection `yaml:"connections" json:"connections"`
}

// ConnectionState is the current connection state returned to the frontend.
type ConnectionState struct {
	Connected   bool               `json:"connected"`
	Attached    bool               `json:"attached"`
	Pid         int                `json:"pid"`
	Output      string             `json:"output"`
	Connections []ProfileConnection `json:"connections"`
}

// doRequest executes an HTTP request with the given timeout using the shared client.
// The context is kept alive until the response body is fully read. Callers receive
// a response whose Body is safe to read without context cancellation races.
func (a *App) doRequest(req *http.Request, timeout time.Duration) (*http.Response, error) {
	ctx, cancel := context.WithTimeout(req.Context(), timeout)
	resp, err := a.httpClient.Do(req.WithContext(ctx))
	if err != nil {
		cancel()
		return nil, err
	}
	// Read the entire body while the context is still alive, then replace
	// resp.Body with an in-memory reader so the caller can read it safely.
	body, err := io.ReadAll(resp.Body)
	resp.Body.Close()
	cancel()
	if err != nil {
		return nil, err
	}
	resp.Body = io.NopCloser(bytes.NewReader(body))
	return resp, nil
}

// NewApp creates a new App instance.
func NewApp() *App {
	jar, _ := cookiejar.New(nil)
	return &App{
		httpClient: &http.Client{
			Jar: jar,
			// No global Timeout -- per-request context timeouts are used
			// via doRequest(). A global timeout would override context
			// deadlines and kill long-running file transfers.
		},
		assignedPorts: make(map[int]bool),
	}
}

func (a *App) startup(ctx context.Context) {
	a.ctx = ctx

	// Apply any pending self-update from a previous run
	a.applyPendingSelfUpdate()

	// Set up system tray icon
	a.setupTray()

	// Apply startup settings
	settings := a.GetSettings()

	// Set default profile: use setting, or find first available profile
	profileMu.Lock()
	if settings.DefaultProfile != "" {
		currentProfileName = settings.DefaultProfile
	} else {
		// Check if default profile exists, otherwise use first available
		defaultPath := filepath.Join(profilesDir(), currentProfileName+".yaml")
		if _, err := os.Stat(defaultPath); os.IsNotExist(err) {
			entries, _ := os.ReadDir(profilesDir())
			for _, e := range entries {
				if !e.IsDir() && filepath.Ext(e.Name()) == ".yaml" {
					currentProfileName = strings.TrimSuffix(e.Name(), ".yaml")
					break
				}
			}
		}
	}
	profileMu.Unlock()

	// Check for updates
	if settings.AutoCheckUpdates {
		go a.checkForUpdates()
	}

}

// checkForUpdates checks if any managed binary (telavisor or tela CLI) is
// behind the latest GitHub release. If so, sets updatePending but does NOT
// auto-download. The user clicks "Restart to Update" to trigger the update.
// Exception: if tela CLI is not installed at all, it is downloaded immediately.
func (a *App) checkForUpdates() {
	latest, err := a.latestRelease()
	if err != nil {
		return // offline
	}

	needsUpdate := false

	// Check telavisor version
	if version != latest {
		needsUpdate = true
	}

	// Check tela CLI version
	bin := "tela"
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	localPath := filepath.Join(telaInstallDir(), bin)

	if _, err := os.Stat(localPath); err != nil {
		// tela not installed -- download it now (first run)
		a.installTool("tela", latest)
	} else {
		// tela exists -- check version
		cmd := exec.Command(localPath, "version")
		hideConsoleWindow(cmd)
		out, _ := cmd.CombinedOutput()
		parts := strings.Fields(strings.TrimSpace(string(out)))
		if len(parts) >= 2 && parts[1] != latest {
			needsUpdate = true
		}
	}

	if needsUpdate {
		a.mu.Lock()
		a.updatePending = true
		a.updateVersion = latest
		a.mu.Unlock()
	}
}

// isPackageManaged returns true if telavisor was installed via a package manager
// (deb, rpm, msi, dmg). In that case, self-update is disabled and the user
// should update via their package manager.
func isPackageManaged() bool {
	exe := selfExePath()
	if exe == "" {
		return false
	}
	// Linux: installed to /usr/bin or /usr/local/bin by deb/rpm
	if strings.HasPrefix(exe, "/usr/bin/") || strings.HasPrefix(exe, "/usr/local/bin/") {
		return true
	}
	// macOS: installed to /Applications
	if strings.HasPrefix(exe, "/Applications/") {
		return true
	}
	// Windows: installed to Program Files
	pf := os.Getenv("ProgramFiles")
	pfx86 := os.Getenv("ProgramFiles(x86)")
	if pf != "" && strings.HasPrefix(strings.ToLower(exe), strings.ToLower(pf)) {
		return true
	}
	if pfx86 != "" && strings.HasPrefix(strings.ToLower(exe), strings.ToLower(pfx86)) {
		return true
	}
	return false
}

// selfExePath returns the absolute path of the currently running telavisor binary.
func selfExePath() string {
	exe, err := os.Executable()
	if err != nil {
		return ""
	}
	exe, _ = filepath.Abs(exe)
	return exe
}

// selfUpdatePath returns the staging path for a pending update (next to the running binary).
func selfUpdatePath() string {
	exe := selfExePath()
	if exe == "" {
		return ""
	}
	ext := filepath.Ext(exe)
	base := strings.TrimSuffix(exe, ext)
	return base + "-update" + ext
}

// applyPendingSelfUpdate checks for a staged update binary and swaps it in place.
func (a *App) applyPendingSelfUpdate() {
	updatePath := selfUpdatePath()
	if updatePath == "" {
		return
	}
	if _, err := os.Stat(updatePath); err != nil {
		return // no pending update
	}

	currentPath := selfExePath()
	if currentPath == "" {
		return
	}

	if runtime.GOOS == "windows" {
		// Can't overwrite running exe -- rename current to .old first
		oldPath := currentPath + ".old"
		os.Remove(oldPath)
		if err := os.Rename(currentPath, oldPath); err != nil {
			log.Printf("[update] failed to rename current binary: %v", err)
			return
		}
		if err := os.Rename(updatePath, currentPath); err != nil {
			// Rollback
			os.Rename(oldPath, currentPath)
			log.Printf("[update] failed to install update: %v", err)
			return
		}
		// Clean up old binary with retry (may be locked briefly)
		go func() {
			for range 10 {
				if os.Remove(oldPath) == nil {
					return
				}
				time.Sleep(500 * time.Millisecond)
			}
		}()
	} else {
		// Unix: just rename over the running binary
		if err := os.Rename(updatePath, currentPath); err != nil {
			log.Printf("[update] failed to install update: %v", err)
			return
		}
		os.Chmod(currentPath, 0755)
	}

	log.Printf("[update] applied pending update")
}


// GetVersion returns the current telavisor version.
func (a *App) GetVersion() string {
	return version
}

// ToolVersions contains version info for all managed binaries.
type ToolVersions struct {
	GUI       string `json:"gui"`
	CLI       string `json:"cli"`
	Latest    string `json:"latest"`
	GUIBehind bool   `json:"guiBehind"`
	CLIBehind bool   `json:"cliBehind"`
}

// GetToolVersions returns versions of all binaries and whether they're behind.
func (a *App) GetToolVersions() ToolVersions {
	tv := ToolVersions{GUI: version}

	// Get CLI version from configured binary path
	bin := "tela"
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	localPath := filepath.Join(a.effectiveBinPath(), bin)
	if _, err := os.Stat(localPath); err == nil {
		cmd := exec.Command(localPath, "version")
		hideConsoleWindow(cmd)
		out, err := cmd.CombinedOutput()
		if err == nil {
			parts := strings.Fields(strings.TrimSpace(string(out)))
			if len(parts) >= 2 {
				tv.CLI = parts[1]
			}
		}
	} else {
		tv.CLI = "not installed"
	}

	// Get latest from cache
	a.mu.Lock()
	tv.Latest = a.updateVersion
	a.mu.Unlock()

	if tv.Latest == "" {
		// Try fetching (may already be cached from checkForUpdates)
		if latest, err := a.latestRelease(); err == nil {
			tv.Latest = latest
		}
	}

	if tv.Latest != "" {
		// Don't flag dev builds as behind -- there's nothing to update to
		tv.GUIBehind = tv.GUI != tv.Latest && tv.GUI != "dev" && tv.GUI != ""
		tv.CLIBehind = tv.CLI != tv.Latest && tv.CLI != "not installed"
	}

	return tv
}

// CheckForUpdatesNow re-checks for updates (called by Refresh button).
func (a *App) CheckForUpdatesNow() {
	a.checkForUpdates()
}

// HasUpdate returns true if a self-update is pending.
func (a *App) HasUpdate() bool {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.updatePending
}

// IsPackageManaged returns true if installed via a package manager.
func (a *App) IsPackageManaged() bool {
	return isPackageManaged()
}

// GetUpdateVersion returns the version of the pending update.
func (a *App) GetUpdateVersion() string {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.updateVersion
}

// UpdateInfo bundles all update-related state for a single frontend call.
type UpdateInfo struct {
	Pending        bool   `json:"pending"`
	Version        string `json:"version"`
	GUI            string `json:"gui"`
	CLI            string `json:"cli"`
	GUIBehind      bool   `json:"guiBehind"`
	CLIBehind      bool   `json:"cliBehind"`
	PackageManaged bool   `json:"packageManaged"`
}

// GetUpdateInfo returns all update state in one call, avoiding nested
// async calls on the frontend.
func (a *App) GetUpdateInfo() UpdateInfo {
	a.mu.Lock()
	pending := a.updatePending
	ver := a.updateVersion
	a.mu.Unlock()

	tv := a.GetToolVersions()

	return UpdateInfo{
		Pending:        pending,
		Version:        ver,
		GUI:            tv.GUI,
		CLI:            tv.CLI,
		GUIBehind:      tv.GUIBehind,
		CLIBehind:      tv.CLIBehind,
		PackageManaged: isPackageManaged(),
	}
}

// RestartToUpdate downloads updates for all binaries and relaunches.
func (a *App) RestartToUpdate() error {
	a.mu.Lock()
	ver := a.updateVersion
	a.mu.Unlock()

	if ver == "" {
		return fmt.Errorf("no update available")
	}

	// Disconnect if connected and wait for process to exit
	a.Disconnect()
	a.waitForProcessExit(5 * time.Second)

	// Update tela CLI
	a.installTool("tela", ver)

	if isPackageManaged() {
		// Package-managed: CLI updated, GUI must be updated via package manager
		a.mu.Lock()
		a.updatePending = false
		a.mu.Unlock()
		return nil
	}

	// Download telavisor update to staging path (next to running binary)
	a.downloadSelfUpdate(ver)

	exe := selfExePath()
	if exe == "" {
		return fmt.Errorf("cannot determine executable path")
	}

	// Apply the update now before relaunching.
	a.applyPendingSelfUpdate()

	// Relaunch from the same path (which is now the new binary)
	cmd := exec.Command(exe)
	cmd.Start()

	os.Exit(0)
	return nil // unreachable
}

// downloadSelfUpdate downloads the telavisor binary for the current platform.
func (a *App) downloadSelfUpdate(ver string) {
	ext := ""
	if runtime.GOOS == "windows" {
		ext = ".exe"
	}
	binaryName := fmt.Sprintf("telavisor-%s-%s%s", runtime.GOOS, runtime.GOARCH, ext)
	url := fmt.Sprintf("https://github.com/paulmooreparks/tela/releases/download/%s/%s", ver, binaryName)

	os.MkdirAll(telaInstallDir(), 0755)
	updatePath := selfUpdatePath()

	resp, err := http.Get(url)
	if err != nil || resp.StatusCode != 200 {
		if resp != nil {
			resp.Body.Close()
		}
		return
	}
	defer resp.Body.Close()

	tmpPath := updatePath + ".tmp"
	f, err := os.Create(tmpPath)
	if err != nil {
		return
	}
	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		os.Remove(tmpPath)
		return
	}
	f.Close()

	os.Remove(updatePath)
	os.Rename(tmpPath, updatePath)

	if runtime.GOOS != "windows" {
		os.Chmod(updatePath, 0755)
	}
}

func (a *App) shutdown(ctx context.Context) {
	a.DisconnectControlWS()

	a.mu.Lock()
	if a.telaProcess != nil {
		killProcessTree(a.telaProcess.Pid)
		a.telaProcess = nil
		a.connected = false
	}
	a.mu.Unlock()

	// Force exit after timeout if goroutines are stuck.
	// Wails expects OnShutdown to return promptly. If the WebSocket
	// reader or output pipe goroutine is still blocking, this ensures
	// the process doesn't hang indefinitely.
	go func() {
		time.Sleep(3 * time.Second)
		os.Exit(0)
	}()
}

// --- Window Management ---

// ShouldAutoConnect returns true if auto-connect is enabled and there's a saved profile.
func (a *App) ShouldAutoConnect() bool {
	settings := a.GetSettings()
	if !settings.AutoConnect {
		return false
	}
	// Check if there's a saved profile with connections
	connections := a.LoadProfile()
	return len(connections) > 0
}

// ShowWindow brings the window back from the system tray.
func (a *App) ShowWindow() {
	wailsRuntime.WindowShow(a.ctx)
	wailsRuntime.WindowSetAlwaysOnTop(a.ctx, true)
	wailsRuntime.WindowSetAlwaysOnTop(a.ctx, false)
}

// QuitApp initiates application exit. The actual confirmation and
// cleanup happen in OnBeforeClose.
func (a *App) QuitApp() {
	a.mu.Lock()
	a.quitting = true
	a.mu.Unlock()

	wailsRuntime.EventsEmit(a.ctx, "app:quitting")

	go func() {
		done := make(chan struct{})
		go func() {
			a.Disconnect()
			a.DisconnectControlWS()
			close(done)
		}()

		select {
		case <-done:
			// Clean disconnect succeeded
			wailsRuntime.Quit(a.ctx)
		case <-time.After(10 * time.Second):
			// Disconnect is stuck -- ask user
			wailsRuntime.EventsEmit(a.ctx, "app:quit-stuck")
			<-done // wait for user to force-kill or for it to finally finish
			wailsRuntime.Quit(a.ctx)
		}
	}()
}

// ForceQuit kills the tela process tree and exits immediately.
func (a *App) ForceQuit() {
	a.mu.Lock()
	if a.telaProcess != nil {
		killProcessTree(a.telaProcess.Pid)
		a.telaProcess.Kill()
		a.telaProcess = nil
	}
	a.connected = false
	a.mu.Unlock()
	os.Exit(0)
}

// confirmQuit is called by OnBeforeClose when no confirmation is needed.
func (a *App) confirmQuit() {
	a.mu.Lock()
	a.quitting = true
	a.mu.Unlock()

	wailsRuntime.EventsEmit(a.ctx, "app:quitting")

	go func() {
		a.Disconnect()
		a.DisconnectControlWS()
		wailsRuntime.Quit(a.ctx)
	}()
}

// IsQuitting returns true if the app is in the process of quitting.
func (a *App) IsQuitting() bool {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.quitting
}

// IsConnected returns true if tela is currently connected.
func (a *App) IsConnected() bool {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.connected
}

// ConfirmDisconnect shows a native confirmation dialog if connected
// and the confirmDisconnect setting is enabled.
// Returns true if not connected, confirmation is disabled, or user confirms.
func (a *App) ConfirmDisconnect() bool {
	if !a.IsConnected() {
		return true
	}
	a.mu.Lock()
	isAttached := a.attached
	a.mu.Unlock()

	// Attached mode: no confirmation needed (detach is non-destructive)
	if isAttached {
		return true
	}

	s := a.GetSettings()
	if !s.ConfirmDisconnect {
		return true
	}
	result, _ := wailsRuntime.MessageDialog(a.ctx, wailsRuntime.MessageDialogOptions{
		Type:          wailsRuntime.QuestionDialog,
		Title:         "Disconnect",
		Message:       "Are you sure you want to disconnect?",
		DefaultButton: "No",
		Buttons:       []string{"Yes", "No"},
	})
	return result == "Yes"
}

// ConfirmDialog shows a native confirmation dialog and returns the user's choice.
func (a *App) ConfirmDialog(title, message string) bool {
	result, _ := wailsRuntime.MessageDialog(a.ctx, wailsRuntime.MessageDialogOptions{
		Type:          wailsRuntime.QuestionDialog,
		Title:         title,
		Message:       message,
		DefaultButton: "No",
		Buttons:       []string{"Yes", "No"},
	})
	return result == "Yes"
}

// --- Command Log ---

// GetCommandLog returns all command log entries.
func (a *App) GetCommandLog() []CommandLogEntry {
	a.mu.Lock()
	defer a.mu.Unlock()
	result := make([]CommandLogEntry, len(a.cmdLog))
	copy(result, a.cmdLog)
	return result
}

// doRequestLogged is like doRequest but logs the completed request to the command log.
// Use for user-initiated operations (admin API, file share). Do not use for background polls.
func (a *App) doRequestLogged(req *http.Request, timeout time.Duration) (*http.Response, error) {
	resp, err := a.doRequest(req, timeout)
	if err != nil {
		return nil, err
	}
	a.logCommandWithMethod(req.Method,
		fmt.Sprintf("%s %s -> %d", req.Method, req.URL.Path, resp.StatusCode),
		fmt.Sprintf("%s %s -> %d", req.Method, req.URL.String(), resp.StatusCode))
	return resp, nil
}

func (a *App) logCommand(description, command string) {
	a.logCommandWithMethod("CLI", description, command)
}

func (a *App) logCommandWithMethod(method, description, command string) {
	entry := CommandLogEntry{
		Time:        time.Now().UTC().Format(time.RFC3339),
		Method:      method,
		Description: description,
		Command:     command,
	}
	a.mu.Lock()
	a.cmdLog = append(a.cmdLog, entry)
	a.mu.Unlock()

	// Emit to frontend for real-time command log
	if a.ctx != nil {
		wailsRuntime.EventsEmit(a.ctx, "app:command", map[string]string{
			"time":        entry.Time,
			"method":      entry.Method,
			"description": entry.Description,
			"command":     entry.Command,
		})
	}
}

// --- Local Registry ---

func telaConfigDir() string {
	if runtime.GOOS == "windows" {
		if appData := os.Getenv("APPDATA"); appData != "" {
			return filepath.Join(appData, "tela")
		}
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tela")
}

func profilesDir() string {
	return filepath.Join(telaConfigDir(), "profiles")
}

func profilePath() string {
	profileMu.RLock()
	name := currentProfileName
	profileMu.RUnlock()
	return filepath.Join(profilesDir(), name+".yaml")
}

// GetKnownHubs returns all hubs the user has configured locally.
// Reads from credentials.yaml and hubs.yaml.
func (a *App) GetKnownHubs() []KnownHub {
	seen := make(map[string]bool)
	var hubs []KnownHub

	// 1. Credential store -- hubs with stored tokens
	store, err := credstore.Load(credstore.UserPath())
	if err == nil && store != nil {
		for url, cred := range store.Hubs {
			name := hubNameFromURL(url)
			hubs = append(hubs, KnownHub{
				Name:     name,
				URL:      url,
				HasToken: cred.Token != "",
				Source:   "credentials",
			})
			seen[url] = true
		}
	}

	// 2. Hub aliases -- short names mapped to URLs
	hubsFile := filepath.Join(telaConfigDir(), "hubs.yaml")
	if data, err := os.ReadFile(hubsFile); err == nil {
		var cfg struct {
			Hubs map[string]string `yaml:"hubs"`
		}
		if yaml.Unmarshal(data, &cfg) == nil {
			for name, url := range cfg.Hubs {
				if !seen[url] {
					hasToken := false
					if store != nil {
						_, hasToken = store.Hubs[url]
					}
					hubs = append(hubs, KnownHub{
						Name:     name,
						URL:      url,
						HasToken: hasToken,
						Source:   "hubs",
					})
					seen[url] = true
				}
			}
		}
	}

	return hubs
}

func hubNameFromURL(url string) string {
	url = strings.TrimPrefix(url, "wss://")
	url = strings.TrimPrefix(url, "ws://")
	url = strings.TrimPrefix(url, "https://")
	url = strings.TrimPrefix(url, "http://")
	url = strings.TrimSuffix(url, "/")
	return url
}

// GetHubStatus queries a hub for its machine/service status.
func (a *App) GetHubStatus(hubURL string) HubStatus {
	token := credstore.LookupToken(hubURL)
	if token == "" {
		return HubStatus{Error: "no token stored for this hub"}
	}

	// Convert wss:// to https:// for the API call
	apiURL := hubURL
	apiURL = strings.Replace(apiURL, "wss://", "https://", 1)
	apiURL = strings.Replace(apiURL, "ws://", "http://", 1)
	apiURL = strings.TrimSuffix(apiURL, "/") + "/api/status"

	req, err := http.NewRequest("GET", apiURL, nil)
	if err != nil {
		return HubStatus{Error: err.Error()}
	}
	req.Header.Set("Authorization", "Bearer "+token)

	resp, err := a.doRequest(req, 15*time.Second)
	if err != nil {
		return HubStatus{Error: err.Error()}
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return HubStatus{Error: fmt.Sprintf("HTTP %d", resp.StatusCode)}
	}

	var raw struct {
		HubName  string `json:"hubName"`
		Machines []struct {
			ID             string `json:"id"`
			Hostname       string `json:"hostname"`
			OS             string `json:"os"`
			AgentConnected bool   `json:"agentConnected"`
			SessionCount   int    `json:"sessionCount"`
			LastSeen       string `json:"lastSeen"`
			Services       []struct {
				Name  string `json:"name"`
				Port  int    `json:"port"`
				Proto string `json:"proto"`
			} `json:"services"`
		} `json:"machines"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&raw); err != nil {
		return HubStatus{Error: err.Error()}
	}

	status := HubStatus{
		Online:  true,
		HubName: raw.HubName,
	}
	for _, m := range raw.Machines {
		ms := MachineStatus{
			ID:             m.ID,
			Hostname:       m.Hostname,
			OS:             m.OS,
			AgentConnected: m.AgentConnected,
			SessionCount:   m.SessionCount,
			LastSeen:       m.LastSeen,
		}
		for _, s := range m.Services {
			ms.Services = append(ms.Services, ServiceInfo{
				Name:  s.Name,
				Port:  s.Port,
				Proto: s.Proto,
			})
		}
		status.Machines = append(status.Machines, ms)
	}
	return status
}

// --- Hub Management ---

// AddHub stores a hub URL and token in the credential store.
func (a *App) AddHub(url, token string) error {
	wsURL := toWSURL(url)
	a.logCommand("Add hub "+wsURL, "tela login "+wsURL)

	store, err := credstore.Load(credstore.UserPath())
	if err != nil {
		store = &credstore.Store{Hubs: make(map[string]credstore.Credential)}
	}
	store.Set(wsURL, credstore.Credential{Token: token})
	return store.Save(credstore.UserPath())
}

// RemoveHub removes a hub from the credential store.
func (a *App) RemoveHub(url string) error {
	wsURL := toWSURL(url)
	a.logCommand("Remove hub "+wsURL, "tela logout "+wsURL)

	// Remove from credential store
	store, err := credstore.Load(credstore.UserPath())
	if err == nil {
		store.Remove(wsURL)
		store.Save(credstore.UserPath())
	}

	// Remove from hubs.yaml aliases
	hubsFile := filepath.Join(telaConfigDir(), "hubs.yaml")
	if data, err := os.ReadFile(hubsFile); err == nil {
		var cfg struct {
			Hubs map[string]string `yaml:"hubs"`
		}
		if yaml.Unmarshal(data, &cfg) == nil && cfg.Hubs != nil {
			changed := false
			for name, hubURL := range cfg.Hubs {
				if hubURL == url || hubURL == wsURL {
					delete(cfg.Hubs, name)
					changed = true
				}
			}
			if changed {
				out, _ := yaml.Marshal(&cfg)
				os.WriteFile(hubsFile, out, 0600)
			}
		}
	}

	return nil
}

// GetStoredToken checks the credential store for a token for the given hub URL.
func (a *App) GetStoredToken(hubURL string) string {
	return credstore.LookupToken(toWSURL(hubURL))
}

// --- Hub Admin API ---

// maskToken returns a masked version of a token for logging: "7bf042ce..."
func maskToken(token string) string {
	if len(token) <= 8 {
		return "****"
	}
	return token[:8] + "..."
}

// adminAPICall makes an authenticated request to a hub's admin API.
// It logs every call to the command log as a curl command with the token masked.
func (a *App) adminAPICall(hubURL, method, path string, body []byte) ([]byte, error) {
	token := credstore.LookupToken(toWSURL(hubURL))
	if token == "" {
		return nil, fmt.Errorf("no token stored for this hub")
	}

	apiURL := strings.Replace(hubURL, "wss://", "https://", 1)
	apiURL = strings.Replace(apiURL, "ws://", "http://", 1)
	apiURL = strings.TrimSuffix(apiURL, "/") + path

	// Log mutating requests automatically. GETs are logged by callers when user-initiated.
	if method != "GET" {
		masked := maskToken(token)
		curlCmd := "curl -X " + method + " " + apiURL + " \\\n  -H \"Authorization: Bearer " + masked + "\""
		if body != nil {
			curlCmd += " \\\n  -H \"Content-Type: application/json\" \\\n  -d '" + string(body) + "'"
		}
		// HTTP logging handled by doRequest
	}

	var bodyReader io.Reader
	if body != nil {
		bodyReader = bytes.NewReader(body)
	}

	req, err := http.NewRequest(method, apiURL, bodyReader)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := a.doRequestLogged(req, 15*time.Second)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errResp struct {
			Error string `json:"error"`
		}
		if json.Unmarshal(respBody, &errResp) == nil && errResp.Error != "" {
			return nil, fmt.Errorf("%s", errResp.Error)
		}
		return nil, fmt.Errorf("HTTP %d", resp.StatusCode)
	}

	return respBody, nil
}

// LogAdminGET is a no-op retained for frontend compatibility.
// HTTP logging is handled automatically by doRequest.
func (a *App) LogAdminGET(hubURL, path string) {}

// AdminListTokens returns the token list from a hub's admin API.
func (a *App) AdminListTokens(hubURL string) string {
	data, err := a.adminAPICall(hubURL, "GET", "/api/admin/tokens", nil)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminCreateToken creates a new token identity on a hub.
func (a *App) AdminCreateToken(hubURL, id, role string) string {
	body, _ := json.Marshal(map[string]string{"id": id, "role": role})
	data, err := a.adminAPICall(hubURL, "POST", "/api/admin/tokens", body)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminDeleteToken removes a token identity from a hub.
func (a *App) AdminDeleteToken(hubURL, id string) string {
	data, err := a.adminAPICall(hubURL, "DELETE", "/api/admin/tokens?id="+url.QueryEscape(id), nil)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminRotateToken regenerates a token for an identity on a hub.
func (a *App) AdminRotateToken(hubURL, id string) string {
	data, err := a.adminAPICall(hubURL, "POST", "/api/admin/rotate/"+url.QueryEscape(id), nil)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminListACLs returns the ACL rules from a hub's admin API.
func (a *App) AdminListACLs(hubURL string) string {
	data, err := a.adminAPICall(hubURL, "GET", "/api/admin/acls", nil)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminGrantConnect grants connect access to an identity for a machine.
func (a *App) AdminGrantConnect(hubURL, id, machineId string) string {
	body, _ := json.Marshal(map[string]string{"id": id, "machineId": machineId})
	data, err := a.adminAPICall(hubURL, "POST", "/api/admin/grant", body)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminRevokeConnect revokes connect access from an identity for a machine.
func (a *App) AdminRevokeConnect(hubURL, id, machineId string) string {
	body, _ := json.Marshal(map[string]string{"id": id, "machineId": machineId})
	data, err := a.adminAPICall(hubURL, "POST", "/api/admin/revoke", body)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminGrantRegister grants register access to an identity for a machine.
func (a *App) AdminGrantRegister(hubURL, id, machineId string) string {
	body, _ := json.Marshal(map[string]string{"id": id, "machineId": machineId})
	data, err := a.adminAPICall(hubURL, "POST", "/api/admin/grant-register", body)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminRevokeRegister revokes register access from an identity for a machine.
func (a *App) AdminRevokeRegister(hubURL, id, machineId string) string {
	body, _ := json.Marshal(map[string]string{"id": id, "machineId": machineId})
	data, err := a.adminAPICall(hubURL, "POST", "/api/admin/revoke-register", body)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminListPortals returns the portal registrations from a hub's admin API.
func (a *App) AdminListPortals(hubURL string) string {
	data, err := a.adminAPICall(hubURL, "GET", "/api/admin/portals", nil)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// AdminGeneratePairCode generates a pairing code on a hub.
func (a *App) AdminGeneratePairCode(hubURL, pairType, role, machineId string, expiresIn string) string {
	payload := map[string]any{"type": pairType, "role": role}
	if machineId != "" {
		payload["machineId"] = machineId
	}
	if expiresIn != "" {
		payload["expiresIn"] = expiresIn
	}
	body, _ := json.Marshal(payload)
	data, err := a.adminAPICall(hubURL, "POST", "/api/admin/pair-code", body)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// GetHubInfo returns extended hub info from /api/status (hub metadata).
func (a *App) GetHubInfo(hubURL string) string {
	data, err := a.adminAPICall(hubURL, "GET", "/api/status", nil)
	if err != nil {
		return `{"error":"` + err.Error() + `"}`
	}
	return string(data)
}

// GetTokenRole returns the role of the stored token by checking the token list.
func (a *App) GetTokenRole(hubURL string) string {
	token := credstore.LookupToken(toWSURL(hubURL))
	if token == "" {
		return "unknown"
	}
	data, err := a.adminAPICall(hubURL, "GET", "/api/admin/tokens", nil)
	if err != nil {
		return "user" // can't determine, assume user
	}
	preview := token
	if len(preview) > 8 {
		preview = preview[:8] + "..."
	}
	var resp struct {
		Tokens []struct {
			ID           string `json:"id"`
			Role         string `json:"role"`
			TokenPreview string `json:"tokenPreview"`
		} `json:"tokens"`
	}
	if json.Unmarshal(data, &resp) == nil {
		for _, t := range resp.Tokens {
			if t.TokenPreview == preview {
				return t.Role
			}
		}
	}
	return "user"
}

// --- Docker Integration ---

// DockerGetToken runs telahubd user show-owner inside a Docker container.
func (a *App) DockerGetToken(container, role string) (string, error) {
	if role == "" {
		role = "show-owner"
	}
	cmd := fmt.Sprintf("docker exec %s telahubd user %s -config /app/data/telahubd.yaml",
		container, role)
	a.logCommand("Get "+role+" token from container "+container, cmd)

	out, err := exec.Command("docker", "exec", container,
		"telahubd", "user", role, "-config", "/app/data/telahubd.yaml").CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s: %s", err, strings.TrimSpace(string(out)))
	}
	return strings.TrimSpace(string(out)), nil
}

// DockerListContainers lists running Docker containers (for hub discovery).
func (a *App) DockerListContainers() ([]string, error) {
	out, err := exec.Command("docker", "ps", "--format", "{{.Names}}").CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("docker not available: %s", strings.TrimSpace(string(out)))
	}
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	var names []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" {
			names = append(names, line)
		}
	}
	return names, nil
}

// --- Profile-Based Connection ---

// AssignLocalPort picks a unique local port for a service. Checks system
// availability AND avoids ports already assigned to other selected services.
func (a *App) AssignLocalPort(servicePort int) int {
	a.mu.Lock()
	defer a.mu.Unlock()

	// Try the advertised port first
	if !a.assignedPorts[servicePort] && isPortAvailable(servicePort) {
		a.assignedPorts[servicePort] = true
		return servicePort
	}

	// Try port + 10000, then increment until we find one
	candidate := servicePort + 10000
	for i := 0; i < 100; i++ {
		if !a.assignedPorts[candidate] && isPortAvailable(candidate) {
			a.assignedPorts[candidate] = true
			return candidate
		}
		candidate++
	}

	// Last resort
	a.assignedPorts[servicePort] = true
	return servicePort
}

// PortRequest is a service that needs a local port assigned.
type PortRequest struct {
	Key         string `json:"key"`         // unique key like "hub||machine||service"
	ServicePort int    `json:"servicePort"` // the advertised remote port
}

// PortAssignment is the result of port resolution.
type PortAssignment struct {
	Key       string `json:"key"`
	LocalPort int    `json:"localPort"`
}

// ResolveAllPorts takes all selected services and assigns clash-free local ports.
// Called whenever selections change. Resets all previous assignments.
func (a *App) ResolveAllPorts(requestsJSON string) ([]PortAssignment, error) {
	var requests []PortRequest
	if err := json.Unmarshal([]byte(requestsJSON), &requests); err != nil {
		return nil, fmt.Errorf("invalid requests: %w", err)
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	// Reset all assignments
	a.assignedPorts = make(map[int]bool)

	var results []PortAssignment
	for _, req := range requests {
		port := req.ServicePort

		// Try the advertised port
		if !a.assignedPorts[port] && isPortAvailable(port) {
			a.assignedPorts[port] = true
			results = append(results, PortAssignment{Key: req.Key, LocalPort: port})
			continue
		}

		// Try port + 10000, then increment
		candidate := port + 10000
		found := false
		for i := 0; i < 100; i++ {
			if !a.assignedPorts[candidate] && isPortAvailable(candidate) {
				a.assignedPorts[candidate] = true
				results = append(results, PortAssignment{Key: req.Key, LocalPort: candidate})
				found = true
				break
			}
			candidate++
		}
		if !found {
			// Last resort -- use the original port
			a.assignedPorts[port] = true
			results = append(results, PortAssignment{Key: req.Key, LocalPort: port})
		}
	}

	return results, nil
}

// ReleaseLocalPort frees a previously assigned port.
func (a *App) ReleaseLocalPort(port int) {
	a.mu.Lock()
	defer a.mu.Unlock()
	delete(a.assignedPorts, port)
}

func isPortAvailable(port int) bool {
	// Check both loopback and all interfaces (Docker binds on 0.0.0.0)
	for _, addr := range []string{"127.0.0.1", "0.0.0.0"} {
		ln, err := net.Listen("tcp", fmt.Sprintf("%s:%d", addr, port))
		if err != nil {
			return false
		}
		ln.Close()
	}
	return true
}

// LoadProfile reads the saved profile and returns its connections.
func (a *App) LoadProfile() []ProfileConnection {
	data, err := os.ReadFile(profilePath())
	if err != nil {
		return nil
	}
	var profile Profile
	if err := yaml.Unmarshal(data, &profile); err != nil {
		return nil
	}
	return profile.Connections
}

// SaveProfile writes the profile YAML and returns its path.
func (a *App) SaveProfile(connectionsJSON string) (string, error) {
	var connections []ProfileConnection
	if err := json.Unmarshal([]byte(connectionsJSON), &connections); err != nil {
		return "", fmt.Errorf("invalid connections: %w", err)
	}

	// Do not embed tokens in the profile. tela connect -profile
	// resolves tokens from the credential store at connect time.
	// This avoids duplicating credentials across files.
	for i := range connections {
		connections[i].Token = ""
	}

	profile := Profile{Connections: connections}

	data, err := yaml.Marshal(profile)
	if err != nil {
		return "", fmt.Errorf("marshal profile: %w", err)
	}

	dir := profilesDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return "", fmt.Errorf("create profiles dir: %w", err)
	}

	path := profilePath()
	if err := os.WriteFile(path, data, 0600); err != nil {
		return "", fmt.Errorf("write profile: %w", err)
	}

	return path, nil
}

// Connect starts tela connect -profile telavisor in the background.
// TryAttach is called by the frontend after event listeners are registered.
// It checks for a running tela and emits tela:attached if found.
func (a *App) TryAttach() bool {
	if a.AttachToExisting() {
		if a.ctx != nil {
			wailsRuntime.EventsEmit(a.ctx, "tela:attached", true)
		}
		return true
	}
	return false
}

// AttachToExisting checks if tela is already running (service, terminal, etc.)
// and attaches to it without launching a new process. Returns true if attached.
func (a *App) AttachToExisting() bool {
	a.mu.Lock()
	if a.connected {
		a.mu.Unlock()
		return true
	}
	a.mu.Unlock()

	base, token, err := controlEndpoint()
	if err != nil {
		return false
	}

	// Probe the control API
	req, _ := http.NewRequest("GET", base+"/services", nil)
	req.Header.Set("Authorization", "Bearer "+token)
	resp, err := a.doRequest(req, 3*time.Second)
	if err != nil {
		return false
	}
	resp.Body.Close()
	if resp.StatusCode != 200 {
		return false
	}

	// tela is running externally -- attach
	a.mu.Lock()
	a.connected = true
	a.attached = true
	a.telaProcess = nil
	a.mu.Unlock()

	log.Printf("[telavisor] attached to existing tela at %s", base)
	return true
}

// Detach disconnects TV from an externally-running tela without stopping it.
func (a *App) Detach() {
	a.mu.Lock()
	a.connected = false
	a.attached = false
	a.telaProcess = nil
	a.mu.Unlock()
	a.DisconnectControlWS()
	a.logCommand("Detached", "Disconnected from external tela (process still running)")
}

func (a *App) Connect(connectionsJSON string) (string, error) {
	a.mu.Lock()
	if a.connected {
		a.mu.Unlock()
		return "", fmt.Errorf("already connected -- disconnect first")
	}
	a.mu.Unlock()

	// Check if tela is already running externally
	if a.AttachToExisting() {
		if a.ctx != nil {
			wailsRuntime.EventsEmit(a.ctx, "tela:attached", true)
		}
		return "Attached to running tela", nil
	}

	telaPath := a.findTool("tela")
	if telaPath == "" {
		// Auto-download from GitHub
		var err error
		telaPath, err = a.EnsureTool("tela")
		if err != nil {
			return "", fmt.Errorf("tela not available and download failed: %w", err)
		}
	}

	path, err := a.SaveProfile(connectionsJSON)
	if err != nil {
		return "", err
	}

	cmdStr := "tela connect -profile " + path
	a.logCommand("Connect using profile", cmdStr)

	cmd := exec.Command(telaPath, "connect", "-profile", path)
	hideConsoleWindow(cmd)

	outPipe, _ := cmd.StdoutPipe()
	cmd.Stderr = cmd.Stdout

	if err := cmd.Start(); err != nil {
		return "", fmt.Errorf("failed to start tela: %w", err)
	}

	pid := cmd.Process.Pid

	a.mu.Lock()
	a.telaProcess = cmd.Process
	a.connected = true
	a.telaOutput = ""
	a.mu.Unlock()

	go func() {
		buf := make([]byte, 4096)
		for {
			n, err := outPipe.Read(buf)
			if n > 0 {
				chunk := string(buf[:n])
				a.mu.Lock()
				a.telaOutput += chunk
				a.mu.Unlock()
				// Push to frontend in real time
				if a.ctx != nil {
					wailsRuntime.EventsEmit(a.ctx, "tela:output", chunk)
				}
			}
			if err != nil {
				break
			}
		}
		cmd.Wait()
		a.mu.Lock()
		a.connected = false
		a.mu.Unlock()
	}()

	return fmt.Sprintf("Connected (pid %d)", pid), nil
}

// Disconnect stops the tela connection. If attached to an external process,
// it detaches without killing. If TV launched the process, it shuts it down.
func (a *App) Disconnect() error {
	a.mu.Lock()
	isAttached := a.attached
	a.mu.Unlock()

	// Attached to external tela: just detach, don't kill
	if isAttached {
		a.Detach()
		return nil
	}

	// TV launched this process: shut it down
	if a.disconnectViaControlAPI() {
		a.mu.Lock()
		a.telaProcess = nil
		a.connected = false
		a.mu.Unlock()
		return nil
	}

	// Fallback: kill the process directly
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.telaProcess != nil {
		pid := a.telaProcess.Pid
		killProcessTree(pid)
		a.telaProcess.Kill()
		a.telaProcess = nil
		a.connected = false
		a.logCommand("Disconnect (forced)", fmt.Sprintf("taskkill /PID %d /T /F", pid))
		return nil
	}
	a.connected = false
	return nil
}

// disconnectViaControlAPI reads the control file and sends DELETE / to the tela control API.
func (a *App) disconnectViaControlAPI() bool {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return false
	}

	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 || info.Token == "" {
		return false
	}

	url := fmt.Sprintf("http://127.0.0.1:%d/", info.Port)
	req, err := http.NewRequest("DELETE", url, nil)
	if err != nil {
		return false
	}
	req.Header.Set("Authorization", "Bearer "+info.Token)

	resp, err := a.doRequestLogged(req, 5*time.Second)
	if err != nil {
		return false
	}
	defer resp.Body.Close()

	// Wait for the process to exit
	a.mu.Lock()
	proc := a.telaProcess
	a.mu.Unlock()
	if proc != nil {
		// Give it up to 5 seconds to exit gracefully
		done := make(chan struct{})
		go func() {
			proc.Wait()
			close(done)
		}()
		select {
		case <-done:
		case <-time.After(5 * time.Second):
			// Force kill if it doesn't exit
			killProcessTree(proc.Pid)
		}
	}

	return resp.StatusCode == 202
}

// GetConnectionState returns the current connection state.
func (a *App) GetConnectionState() ConnectionState {
	a.mu.Lock()
	defer a.mu.Unlock()

	state := ConnectionState{
		Connected: a.connected,
		Attached:  a.attached,
		Output:    a.telaOutput,
	}

	if a.telaProcess != nil {
		state.Pid = a.telaProcess.Pid
	}

	// Load the saved profile to show connection details
	if a.connected {
		data, err := os.ReadFile(profilePath())
		if err == nil {
			var profile Profile
			if yaml.Unmarshal(data, &profile) == nil {
				state.Connections = profile.Connections
			}
		}
	}

	return state
}

// SetVerbose toggles verbose logging on the running tela instance via control API.
func (a *App) SetVerbose(on bool) error {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return fmt.Errorf("not connected")
	}
	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 {
		return fmt.Errorf("invalid control file")
	}

	req, _ := http.NewRequest("PUT", fmt.Sprintf("http://127.0.0.1:%d/verbose", info.Port), nil)
	req.Header.Set("Authorization", "Bearer "+info.Token)

	resp, err := a.doRequest(req, 3*time.Second)
	if err != nil {
		return fmt.Errorf("control API unreachable: %w", err)
	}
	resp.Body.Close()

	return nil
}

// SaveTerminalOutput saves the terminal output using a save dialog.
func (a *App) SaveTerminalOutput(content string) (string, error) {
	filename := fmt.Sprintf("tela-%s.log", time.Now().Format("2006-01-02-150405"))

	dialog, err := wailsRuntime.SaveFileDialog(a.ctx, wailsRuntime.SaveDialogOptions{
		DefaultFilename: filename,
		Title:           "Save Terminal Output",
		Filters: []wailsRuntime.FileFilter{
			{DisplayName: "Log Files", Pattern: "*.log"},
			{DisplayName: "Text Files", Pattern: "*.txt"},
			{DisplayName: "All Files", Pattern: "*.*"},
		},
	})
	if err != nil {
		return "", fmt.Errorf("dialog failed: %w", err)
	}
	if dialog == "" {
		return "", nil // user cancelled
	}

	if err := os.WriteFile(dialog, []byte(content), 0600); err != nil {
		return "", fmt.Errorf("save failed: %w", err)
	}
	return dialog, nil
}

// PairWithCode exchanges a pairing code for a connect token via the tela CLI.
func (a *App) PairWithCode(hubURL, code string) error {
	telaPath := a.findTool("tela")
	if telaPath == "" {
		// Try to download
		var err error
		telaPath, err = a.EnsureTool("tela")
		if err != nil {
			return fmt.Errorf("tela not available: %w", err)
		}
	}

	wsURL := toWSURL(hubURL)
	cmdStr := "tela pair -hub " + wsURL + " -code " + code
	a.logCommand("Pair with hub "+wsURL, cmdStr)

	cmd := exec.Command(telaPath, "pair", "-hub", wsURL, "-code", code)
	hideConsoleWindow(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		output := strings.TrimSpace(string(out))
		if output != "" {
			return fmt.Errorf("%s", output)
		}
		return fmt.Errorf("pairing failed: %w", err)
	}

	return nil
}

// DetectCredentialType returns "code" if the input looks like a pairing code,
// "token" if it looks like a hex token, or "unknown".
func (a *App) DetectCredentialType(input string) string {
	input = strings.TrimSpace(input)
	// Pairing code: 4-4 alphanumeric with dash (e.g., ABCD-1234)
	if len(input) == 9 && input[4] == '-' {
		return "code"
	}
	// Hex token: 64 hex characters
	if len(input) == 64 {
		allHex := true
		for _, c := range input {
			if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
				allHex = false
				break
			}
		}
		if allHex {
			return "token"
		}
	}
	return "unknown"
}

// --- WebSocket Control Connection ---

// ConnectControlWS connects to the tela control API WebSocket for real-time events.
// Events are forwarded to the frontend via Wails runtime events.
func (a *App) ConnectControlWS() error {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return fmt.Errorf("no control file: %w", err)
	}
	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 {
		return fmt.Errorf("invalid control file")
	}

	wsURL := fmt.Sprintf("ws://127.0.0.1:%d/ws", info.Port)

	conn, _, err := websocket.DefaultDialer.Dial(wsURL, nil)
	if err != nil {
		return fmt.Errorf("ws connect failed: %w", err)
	}

	// Authenticate via first message (avoids token in URL).
	if err := conn.WriteMessage(websocket.TextMessage, []byte(info.Token)); err != nil {
		conn.Close()
		return fmt.Errorf("ws auth failed: %w", err)
	}

	a.mu.Lock()
	// Close any existing connection before replacing.
	if a.controlWS != nil {
		a.controlWS.Close()
	}
	a.controlWS = conn
	a.mu.Unlock()

	// Read events and forward to frontend. When the connection is
	// closed (by DisconnectControlWS or the remote side), ReadMessage
	// returns an error and the goroutine exits. We nil controlWS only
	// if it still points to this connection (avoids clearing a
	// replacement connection opened by a subsequent ConnectControlWS).
	go func() {
		defer func() {
			a.mu.Lock()
			wasAttached := a.attached
			stillOurs := a.controlWS == conn
			if stillOurs {
				a.controlWS = nil
			}
			a.mu.Unlock()

			// If the WebSocket closed unexpectedly while we were attached,
			// the external tela process likely died. Reset to disconnected.
			if stillOurs && wasAttached {
				a.mu.Lock()
				a.connected = false
				a.attached = false
				a.mu.Unlock()
				if a.ctx != nil {
					wailsRuntime.EventsEmit(a.ctx, "tela:disconnected", true)
				}
				log.Printf("[telavisor] control WebSocket closed -- external tela may have exited")
			}
		}()

		for {
			_, message, err := conn.ReadMessage()
			if err != nil {
				return
			}
			wailsRuntime.EventsEmit(a.ctx, "tela:event", string(message))
		}
	}()

	return nil
}

// DisconnectControlWS closes the WebSocket connection.
func (a *App) DisconnectControlWS() {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.controlWS != nil {
		a.controlWS.Close()
		a.controlWS = nil
	}
}

// SendControlCommand sends a command to tela via the WebSocket.
func (a *App) SendControlCommand(cmdJSON string) error {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.controlWS == nil {
		return fmt.Errorf("not connected to control API")
	}
	return a.controlWS.WriteMessage(websocket.TextMessage, []byte(cmdJSON))
}

// GetControlServices returns services from the tela control API.
func (a *App) GetControlServices() []map[string]interface{} {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return nil
	}
	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 {
		return nil
	}

	req, _ := http.NewRequest("GET", fmt.Sprintf("http://127.0.0.1:%d/services", info.Port), nil)
	req.Header.Set("Authorization", "Bearer "+info.Token)
	resp, err := a.doRequest(req, 2*time.Second)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()

	var result []map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	return result
}

// GetControlConnections returns connection info from the tela control API.
func (a *App) GetControlConnections() []map[string]interface{} {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return nil
	}
	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 {
		return nil
	}

	req, _ := http.NewRequest("GET", fmt.Sprintf("http://127.0.0.1:%d/connections", info.Port), nil)
	req.Header.Set("Authorization", "Bearer "+info.Token)
	resp, err := a.doRequest(req, 2*time.Second)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()

	var result []map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	return result
}

// GetControlStatus reads live status from the tela control API.
func (a *App) GetControlStatus() map[string]interface{} {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return nil
	}

	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 {
		return nil
	}

	req, _ := http.NewRequest("GET", fmt.Sprintf("http://127.0.0.1:%d/", info.Port), nil)
	req.Header.Set("Authorization", "Bearer "+info.Token)

	resp, err := a.doRequest(req, 3*time.Second)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	return result
}

// AdminAPICall is the public Wails binding for adminAPICall.
func (a *App) AdminAPICall(hubURL, method, path string, bodyJSON string) string {
	var body []byte
	if bodyJSON != "" {
		body = []byte(bodyJSON)
	}
	data, err := a.adminAPICall(hubURL, method, path, body)
	if err != nil {
		return `{"error":"` + strings.ReplaceAll(err.Error(), `"`, `'`) + `"}`
	}
	return string(data)
}

// --- Agents Mode ---

// AgentInfo contains the data for one agent displayed in Agents mode.
type AgentInfo struct {
	ID             string                 `json:"id"`
	Hub            string                 `json:"hub"`
	Online         bool                   `json:"online"`
	Version        string                 `json:"version"`
	Hostname       string                 `json:"hostname"`
	OS             string                 `json:"os"`
	SessionCount   int                    `json:"sessionCount"`
	RegisteredAt   string                 `json:"registeredAt"`
	LastSeen       string                 `json:"lastSeen"`
	Services       []map[string]interface{} `json:"services"`
	Capabilities   map[string]interface{} `json:"capabilities"`
}

// GetAgentList returns agent info for all machines across all hubs
// in the current profile.
func (a *App) GetAgentList() []AgentInfo {
	var result []AgentInfo

	data, err := os.ReadFile(profilePath())
	if err != nil {
		return result
	}
	var profile Profile
	if yaml.Unmarshal(data, &profile) != nil {
		return result
	}

	hubsSeen := map[string]bool{}
	for _, conn := range profile.Connections {
		if hubsSeen[conn.Hub] {
			continue
		}
		hubsSeen[conn.Hub] = true

		statusData, err := a.adminAPICall(conn.Hub, "GET", "/api/status", nil)
		if err != nil {
			continue
		}
		var status struct {
			Machines []struct {
				ID             string                 `json:"id"`
				AgentConnected bool                   `json:"agentConnected"`
				AgentVersion   *string                `json:"agentVersion"`
				Hostname       *string                `json:"hostname"`
				OS             *string                `json:"os"`
				SessionCount   int                    `json:"sessionCount"`
				RegisteredAt   *string                `json:"registeredAt"`
				LastSeen       *string                `json:"lastSeen"`
				Services       []map[string]interface{} `json:"services"`
				Capabilities   map[string]interface{} `json:"capabilities"`
			} `json:"machines"`
		}
		if json.Unmarshal(statusData, &status) != nil {
			continue
		}

		hubName := hubNameFromURLGo(conn.Hub)
		for _, m := range status.Machines {
			ai := AgentInfo{
				ID:           m.ID,
				Hub:          hubName,
				Online:       m.AgentConnected,
				SessionCount: m.SessionCount,
				Services:     m.Services,
				Capabilities: m.Capabilities,
			}
			if m.AgentVersion != nil { ai.Version = *m.AgentVersion }
			if m.Hostname != nil { ai.Hostname = *m.Hostname }
			if m.OS != nil { ai.OS = *m.OS }
			if m.RegisteredAt != nil { ai.RegisteredAt = *m.RegisteredAt }
			if m.LastSeen != nil { ai.LastSeen = *m.LastSeen }
			result = append(result, ai)
		}
	}
	return result
}

// hubNameFromURLGo extracts a short hub name from a URL (Go-side equivalent).
func hubNameFromURLGo(u string) string {
	u = strings.TrimPrefix(u, "wss://")
	u = strings.TrimPrefix(u, "ws://")
	u = strings.TrimPrefix(u, "https://")
	u = strings.TrimPrefix(u, "http://")
	u = strings.TrimSuffix(u, "/")
	return u
}

// --- File Share ---

// GetMachineCapabilities returns a map of machineID -> capabilities
// by querying the hub status API for each hub in the current profile.
// Uses the stored token if available, but also tries without auth
// (works for open-mode hubs and viewer tokens delivered via cookie).
func (a *App) GetMachineCapabilities() map[string]map[string]interface{} {
	result := make(map[string]map[string]interface{})

	data, err := os.ReadFile(profilePath())
	if err != nil {
		return result
	}
	var profile Profile
	if yaml.Unmarshal(data, &profile) != nil {
		return result
	}

	hubsSeen := map[string]bool{}
	for _, conn := range profile.Connections {
		hubURL := conn.Hub
		if hubsSeen[hubURL] {
			continue
		}
		hubsSeen[hubURL] = true

		// Build the HTTPS URL for the status API
		apiURL := strings.Replace(hubURL, "wss://", "https://", 1)
		apiURL = strings.Replace(apiURL, "ws://", "http://", 1)
		apiURL = strings.TrimSuffix(apiURL, "/") + "/api/status"

		req, err := http.NewRequest("GET", apiURL, nil)
		if err != nil {
			continue
		}

		// Add auth token if available
		token := credstore.LookupToken(toWSURL(hubURL))
		if token != "" {
			req.Header.Set("Authorization", "Bearer "+token)
		}

		resp, err := a.doRequest(req, 10*time.Second)
		if err != nil {
			continue
		}
		respBody, err := io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			continue
		}

		var status struct {
			Machines []struct {
				ID           string                 `json:"id"`
				Capabilities map[string]interface{} `json:"capabilities"`
			} `json:"machines"`
		}
		if json.Unmarshal(respBody, &status) != nil {
			continue
		}
		for _, m := range status.Machines {
			if m.Capabilities != nil {
				result[m.ID] = m.Capabilities
			}
		}
	}
	return result
}

// controlEndpoint reads the control API info and returns (base URL, token).
func controlEndpoint() (string, string, error) {
	controlPath := filepath.Join(telaConfigDir(), "run", "control.json")
	data, err := os.ReadFile(controlPath)
	if err != nil {
		return "", "", fmt.Errorf("no active tela connection")
	}
	var info struct {
		Port  int    `json:"port"`
		Token string `json:"token"`
	}
	if json.Unmarshal(data, &info) != nil || info.Port == 0 {
		return "", "", fmt.Errorf("invalid control file")
	}
	return fmt.Sprintf("http://127.0.0.1:%d", info.Port), info.Token, nil
}

// FileShareRequest sends a file share operation to a connected machine
// via the tela control API's /files proxy.
func (a *App) FileShareRequest(machine string, opJSON string) string {

	base, token, err := controlEndpoint()
	if err != nil {
		return errJSON(err.Error())
	}

	req, _ := http.NewRequest("POST", base+"/files/"+machine, strings.NewReader(opJSON+"\n"))
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := a.doRequestLogged(req, 30*time.Second)
	if err != nil {
		return errJSON("request failed: " + err.Error())
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)

	// Error responses from the proxy use pretty-printed JSON (multiline).
	// Parse them as a whole object rather than splitting on newlines.
	if resp.StatusCode != http.StatusOK {
		var errResp struct {
			Error string `json:"error"`
		}
		if json.Unmarshal(body, &errResp) == nil && errResp.Error != "" {
			return errJSON(errResp.Error)
		}
		return errJSON(fmt.Sprintf("HTTP %d", resp.StatusCode))
	}

	// Success: the file share protocol uses single-line JSON responses
	// (possibly followed by chunk data for reads). Take the first line.
	lines := strings.SplitN(string(body), "\n", 2)
	if len(lines) > 0 {
		return lines[0]
	}
	return errJSON("empty response")
}

// FileShareDownload downloads a file from a connected machine's file share.
// Returns the local path where the file was saved, or an error string.
func (a *App) FileShareDownload(machine string, remotePath string, localPath string) string {
	// HTTP logging handled by doRequest

	base, token, err := controlEndpoint()
	if err != nil {
		return errJSON(err.Error())
	}

	opJSON := fmt.Sprintf(`{"op":"read","path":%s}`, jsonString(remotePath))
	req, _ := http.NewRequest("POST", base+"/files/"+machine, strings.NewReader(opJSON+"\n"))
	req.Header.Set("Authorization", "Bearer "+token)

	resp, err := a.doRequestLogged(req, 300*time.Second)
	if err != nil {
		return errJSON("request failed: " + err.Error())
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return errJSON("read response failed: " + err.Error())
	}

	reader := bufio.NewReader(bytes.NewReader(respBody))

	// Read JSON response header
	headerLine, err := reader.ReadBytes('\n')
	if err != nil {
		return errJSON("read header failed: " + err.Error())
	}
	var fsResp struct {
		OK       bool   `json:"ok"`
		Error    string `json:"error"`
		Size     int64  `json:"size"`
		Checksum string `json:"checksum"`
	}
	if err := json.Unmarshal(headerLine, &fsResp); err != nil {
		return errJSON("invalid response: " + string(headerLine))
	}
	if !fsResp.OK {
		return errJSON(fsResp.Error)
	}

	// Create local file
	f, err := os.Create(localPath)
	if err != nil {
		return errJSON("cannot create file: " + err.Error())
	}
	defer f.Close()

	// Read chunks with checksum verification
	h := sha256.New()
	var totalReceived int64
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			os.Remove(localPath)
			return errJSON(fmt.Sprintf("chunk read error after %d bytes: %v", totalReceived, err))
		}
		line = strings.TrimRight(line, "\n\r")
		if !strings.HasPrefix(line, "CHUNK ") {
			os.Remove(localPath)
			return errJSON(fmt.Sprintf("protocol error after %d bytes: expected CHUNK, got %q", totalReceived, line))
		}
		chunkSize, _ := strconv.ParseInt(strings.TrimPrefix(line, "CHUNK "), 10, 64)
		if chunkSize == 0 {
			break
		}
		n, err := io.CopyN(io.MultiWriter(f, h), reader, chunkSize)
		if err != nil || n != chunkSize {
			os.Remove(localPath)
			return errJSON(fmt.Sprintf("incomplete chunk: wanted %d, got %d: %v", chunkSize, n, err))
		}
		totalReceived += n
	}

	// Verify checksum
	if fsResp.Checksum != "" {
		computed := "sha256:" + hex.EncodeToString(h.Sum(nil))
		if computed != fsResp.Checksum {
			os.Remove(localPath)
			return errJSON("checksum mismatch (file deleted)")
		}
	}

	return fmt.Sprintf(`{"ok":true,"size":%d,"path":%s}`, totalReceived, jsonString(localPath))
}

// FileShareUpload uploads a local file to a connected machine's file share.
func (a *App) FileShareUpload(machine string, localPath string, remoteName string) string {
	// HTTP logging handled by doRequest

	base, token, err := controlEndpoint()
	if err != nil {
		return errJSON(err.Error())
	}

	info, err := os.Stat(localPath)
	if err != nil {
		return errJSON(err.Error())
	}

	// The control API /files proxy expects the full protocol exchange in
	// the request body. We build: JSON header + chunks + CHUNK 0.
	pr, pw := io.Pipe()
	go func() {
		defer pw.Close()

		// Compute checksum
		f, err := os.Open(localPath)
		if err != nil {
			pw.CloseWithError(err)
			return
		}
		h := sha256.New()
		io.Copy(h, f)
		checksum := "sha256:" + hex.EncodeToString(h.Sum(nil))
		f.Seek(0, io.SeekStart)

		// Write request header
		header := fmt.Sprintf(`{"op":"write","path":%s,"size":%d,"checksum":"%s"}`+"\n",
			jsonString(remoteName), info.Size(), checksum)
		pw.Write([]byte(header))

		// Write chunks
		buf := make([]byte, 16384)
		for {
			n, err := f.Read(buf)
			if n > 0 {
				pw.Write([]byte(fmt.Sprintf("CHUNK %d\n", n)))
				pw.Write(buf[:n])
			}
			if err != nil {
				break
			}
		}
		pw.Write([]byte("CHUNK 0\n"))
		f.Close()
	}()

	req, _ := http.NewRequest("POST", base+"/files/"+machine, pr)
	req.Header.Set("Authorization", "Bearer "+token)

	resp, err := a.doRequestLogged(req, 300*time.Second)
	if err != nil {
		return errJSON("upload failed: " + err.Error())
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)

	if resp.StatusCode != http.StatusOK {
		var errResp struct {
			Error string `json:"error"`
		}
		if json.Unmarshal(body, &errResp) == nil && errResp.Error != "" {
			return errJSON(errResp.Error)
		}
		return errJSON(fmt.Sprintf("HTTP %d", resp.StatusCode))
	}

	lines := strings.SplitN(string(body), "\n", 2)
	if len(lines) > 0 {
		return lines[0]
	}
	return errJSON("empty response")
}

func errJSON(msg string) string {
	return fmt.Sprintf(`{"ok":false,"error":%s}`, jsonString(msg))
}

func jsonString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// SaveFileDialog opens a save file dialog and returns the chosen path.
func (a *App) SaveFileDialog(defaultName string) string {
	path, err := wailsRuntime.SaveFileDialog(a.ctx, wailsRuntime.SaveDialogOptions{
		Title:           "Save File",
		DefaultFilename: defaultName,
	})
	if err != nil {
		return ""
	}
	return path
}

// OpenFileDialog opens a file picker and returns the chosen path.
func (a *App) OpenFileDialog() string {
	path, err := wailsRuntime.OpenFileDialog(a.ctx, wailsRuntime.OpenDialogOptions{
		Title: "Select File to Upload",
	})
	if err != nil {
		return ""
	}
	return path
}

// --- Tool Management ---

func (a *App) findTool(name string) string {
	bin := name
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	path := filepath.Join(a.effectiveBinPath(), bin)
	if _, err := os.Stat(path); err == nil {
		return path
	}
	return ""
}

func telaInstallDir() string {
	if runtime.GOOS == "windows" {
		return filepath.Join(os.Getenv("LOCALAPPDATA"), "Tela", "bin")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tela", "bin")
}

// effectiveBinPath returns the configured binary path, or the default if not set.
func (a *App) effectiveBinPath() string {
	s := a.GetSettings()
	if s.BinPath != "" {
		return s.BinPath
	}
	return telaInstallDir()
}

// GetDefaultBinPath returns the platform default binary install directory.
func (a *App) GetDefaultBinPath() string {
	return telaInstallDir()
}

// BinaryInfo describes the status of a managed binary.
type BinaryInfo struct {
	Name      string `json:"name"`
	Path      string `json:"path"`
	Found     bool   `json:"found"`
	Version   string `json:"version"`
	Latest    string `json:"latest"`
	UpToDate  bool   `json:"upToDate"`
}

// ValidateBinPath checks if a path is a valid, accessible directory.
func (a *App) ValidateBinPath(path string) string {
	if path == "" {
		return "" // empty = use default, always valid
	}
	info, err := os.Stat(path)
	if os.IsNotExist(err) {
		return "Directory does not exist. It will be created when you install a binary."
	}
	if err != nil {
		return "Cannot access path: " + err.Error()
	}
	if !info.IsDir() {
		return "Path is not a directory."
	}
	return "" // valid
}

// GetBinStatus checks the status of all managed binaries in the configured path.
func (a *App) GetBinStatus() []BinaryInfo {
	binDir := a.effectiveBinPath()
	latest, _ := a.latestRelease()

	var results []BinaryInfo
	for _, name := range []string{"tela", "telad", "telahubd"} {
		bin := name
		if runtime.GOOS == "windows" {
			bin += ".exe"
		}
		path := filepath.Join(binDir, bin)

		info := BinaryInfo{
			Name:   name,
			Path:   path,
			Latest: latest,
		}

		if _, err := os.Stat(path); err == nil {
			info.Found = true
			// Get version by running binary
			cmd := exec.Command(path, "version")
			hideConsoleWindow(cmd)
			out, err := cmd.CombinedOutput()
			if err == nil {
				parts := strings.Fields(strings.TrimSpace(string(out)))
				if len(parts) >= 2 {
					info.Version = parts[1]
				} else if len(parts) == 1 {
					info.Version = parts[0]
				}
			}
			info.UpToDate = info.Version == latest
		}

		results = append(results, info)
	}
	return results
}

// InstallBinary downloads a specific binary to the configured bin path.
func (a *App) InstallBinary(name string) error {
	binDir := a.effectiveBinPath()
	if err := os.MkdirAll(binDir, 0755); err != nil {
		return fmt.Errorf("create bin dir: %w", err)
	}

	latest, err := a.latestRelease()
	if err != nil {
		return fmt.Errorf("cannot determine latest version: %w", err)
	}

	ext := ""
	if runtime.GOOS == "windows" {
		ext = ".exe"
	}
	binaryName := fmt.Sprintf("%s-%s-%s%s", name, runtime.GOOS, runtime.GOARCH, ext)
	dlURL := fmt.Sprintf("https://github.com/paulmooreparks/tela/releases/download/%s/%s", latest, binaryName)

	resp, err := http.Get(dlURL)
	if err != nil || resp.StatusCode != 200 {
		if resp != nil {
			resp.Body.Close()
		}
		return fmt.Errorf("download %s failed: HTTP %d", name, resp.StatusCode)
	}
	defer resp.Body.Close()

	destPath := filepath.Join(binDir, name+ext)
	f, err := os.Create(destPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", destPath, err)
	}
	_, err = io.Copy(f, resp.Body)
	f.Close()
	if err != nil {
		return fmt.Errorf("write %s: %w", destPath, err)
	}
	os.Chmod(destPath, 0755)

	// Logged by installTool caller
	return nil
}

// BrowseBinPath opens a directory picker and returns the selected path.
func (a *App) BrowseBinPath() string {
	dir, err := wailsRuntime.OpenDirectoryDialog(a.ctx, wailsRuntime.OpenDialogOptions{
		Title: "Select Binary Folder",
	})
	if err != nil {
		return ""
	}
	return dir
}

// EnsureTool checks if a tool is installed, downloads it if not.
func (a *App) EnsureTool(name string) (string, error) {
	path := a.findTool(name)
	if path != "" {
		return path, nil
	}

	version, err := a.latestRelease()
	if err != nil {
		return "", fmt.Errorf("cannot determine latest version: %w", err)
	}

	return a.installTool(name, version)
}

func (a *App) latestRelease() (string, error) {
	req, _ := http.NewRequest("GET", "https://api.github.com/repos/paulmooreparks/tela/releases/latest", nil)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	resp, err := a.doRequest(req, 15*time.Second)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	var release struct {
		TagName string `json:"tag_name"`
	}
	json.NewDecoder(resp.Body).Decode(&release)
	return release.TagName, nil
}

func (a *App) installTool(name, version string) (string, error) {
	ext := ""
	if runtime.GOOS == "windows" {
		ext = ".exe"
	}
	url := fmt.Sprintf("https://github.com/paulmooreparks/tela/releases/download/%s/%s-%s-%s%s",
		version, name, runtime.GOOS, runtime.GOARCH, ext)

	installDir := telaInstallDir()
	os.MkdirAll(installDir, 0755)
	destPath := filepath.Join(installDir, name+ext)

	a.logCommand("Install "+name+" "+version,
		fmt.Sprintf("curl -fSL -o %q %s", destPath, url))

	resp, err := http.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("download failed: HTTP %d", resp.StatusCode)
	}

	// Atomic write: download to temp file, then rename
	tmpPath := destPath + ".tmp"
	f, err := os.Create(tmpPath)
	if err != nil {
		return "", err
	}
	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		os.Remove(tmpPath)
		return "", fmt.Errorf("download incomplete: %w", err)
	}
	f.Close()

	// Replace existing binary atomically
	os.Remove(destPath) // Windows requires removing before rename
	if err := os.Rename(tmpPath, destPath); err != nil {
		os.Remove(tmpPath)
		return "", fmt.Errorf("install failed: %w", err)
	}

	if runtime.GOOS != "windows" {
		os.Chmod(destPath, 0755)
	}
	return destPath, nil
}

// --- Profile Management ---

// currentProfileName tracks which profile is active.
// Protected by profileMu for concurrent access.
var (
	currentProfileName = "telavisor"
	profileMu          sync.RWMutex
)

// ListProfiles returns all available profile names.
func (a *App) ListProfiles() []string {
	dir := profilesDir()
	entries, err := os.ReadDir(dir)
	if err != nil {
		profileMu.RLock()
		fallback := currentProfileName
		profileMu.RUnlock()
		return []string{fallback}
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasSuffix(name, ".yaml") {
			names = append(names, strings.TrimSuffix(name, ".yaml"))
		} else if strings.HasSuffix(name, ".yml") {
			names = append(names, strings.TrimSuffix(name, ".yml"))
		}
	}
	if len(names) == 0 {
		profileMu.RLock()
		fallback := currentProfileName
		profileMu.RUnlock()
		return []string{fallback}
	}
	return names
}

// GetProfilePath returns the file path of the active profile.
func (a *App) GetProfilePath() string {
	return profilePath()
}

// GetCurrentProfile returns the active profile name.
func (a *App) GetCurrentProfile() string {
	profileMu.RLock()
	defer profileMu.RUnlock()
	return currentProfileName
}

// SwitchProfile changes the active profile. Disconnects first if connected.
func (a *App) SwitchProfile(name string) error {
	profileMu.RLock()
	same := name == currentProfileName
	profileMu.RUnlock()
	if same {
		return nil
	}

	// Disconnect if connected and wait for process to exit
	a.Disconnect()
	a.waitForProcessExit(5 * time.Second)

	profileMu.Lock()
	currentProfileName = name
	profileMu.Unlock()
	a.logCommand("Switch profile to "+name, "tela connect -profile "+name)
	return nil
}

// CreateProfile creates a new empty profile.
func (a *App) CreateProfile(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("profile name cannot be empty")
	}

	dir := profilesDir()
	os.MkdirAll(dir, 0700)
	path := filepath.Join(dir, name+".yaml")

	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("profile %q already exists", name)
	}

	content := "connections: []\n"
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("create profile: %w", err)
	}

	a.logCommand("Create profile "+name, "tela profile create "+name)
	return nil
}

// RenameProfile renames a profile file.
func (a *App) RenameProfile(oldName, newName string) error {
	newName = strings.TrimSpace(newName)
	if newName == "" {
		return fmt.Errorf("profile name cannot be empty")
	}

	dir := profilesDir()
	oldPath := filepath.Join(dir, oldName+".yaml")
	newPath := filepath.Join(dir, newName+".yaml")

	if _, err := os.Stat(oldPath); err != nil {
		return fmt.Errorf("profile %q not found", oldName)
	}
	if _, err := os.Stat(newPath); err == nil {
		return fmt.Errorf("profile %q already exists", newName)
	}

	if err := os.Rename(oldPath, newPath); err != nil {
		return fmt.Errorf("rename profile: %w", err)
	}

	profileMu.Lock()
	if currentProfileName == oldName {
		currentProfileName = newName
	}
	profileMu.Unlock()

	return nil
}

// DeleteProfile deletes a profile file.
func (a *App) DeleteProfile(name string) error {
	profileMu.RLock()
	active := currentProfileName
	profileMu.RUnlock()
	if name == active {
		return fmt.Errorf("cannot delete the active profile")
	}
	path := filepath.Join(profilesDir(), name+".yaml")
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("delete profile: %w", err)
	}
	a.logCommand("Delete profile "+name, "tela profile delete "+name)
	return nil
}


// Settings holds user preferences persisted to disk.
type Settings struct {
	AutoConnect      bool   `yaml:"autoConnect" json:"autoConnect"`
	ReconnectOnDrop  bool   `yaml:"reconnectOnDrop" json:"reconnectOnDrop"`
	MinimizeTo       string `yaml:"minimizeTo" json:"minimizeTo"`             // "taskbar" or "tray"
	StartMinimized   bool   `yaml:"startMinimized" json:"startMinimized"`
	MinimizeOnClose  bool   `yaml:"minimizeOnClose" json:"minimizeOnClose"`
	AutoCheckUpdates    bool   `yaml:"autoCheckUpdates" json:"autoCheckUpdates"`
	VerboseDefault      bool   `yaml:"verboseDefault" json:"verboseDefault"`
	ConfirmDisconnect   bool   `yaml:"confirmDisconnect" json:"confirmDisconnect"`
	SidebarWidth        int    `yaml:"sidebarWidth" json:"sidebarWidth"`
	HubsSidebarWidth    int    `yaml:"hubsSidebarWidth" json:"hubsSidebarWidth"`
	DefaultProfile           string `yaml:"defaultProfile" json:"defaultProfile"`
	BinPath                  string `yaml:"binPath" json:"binPath"`
	ConnectTooltipDismissed  bool   `yaml:"connectTooltipDismissed" json:"connectTooltipDismissed"`
	Theme                   string `yaml:"theme" json:"theme"`
}

func defaultSettings() Settings {
	return Settings{
		AutoConnect:      false,
		ReconnectOnDrop:  true,
		MinimizeTo:       "taskbar",
		StartMinimized:   false,
		MinimizeOnClose:  false,
		AutoCheckUpdates:  true,
		VerboseDefault:    false,
		ConfirmDisconnect: true,
		Theme:             "system",
	}
}

func settingsPath() string {
	return filepath.Join(telaConfigDir(), "telavisor-settings.yaml")
}

// GetSettings loads settings from disk, returning defaults if not found.
// Migrates from old telagui-settings.yaml if the new file doesn't exist.
func (a *App) GetSettings() Settings {
	data, err := os.ReadFile(settingsPath())
	if err != nil {
		// Try migrating from old settings file
		oldPath := filepath.Join(telaConfigDir(), "telagui-settings.yaml")
		data, err = os.ReadFile(oldPath)
		if err != nil {
			return defaultSettings()
		}
		// Migrate: write to new path and delete old
		os.WriteFile(settingsPath(), data, 0600)
		os.Remove(oldPath)
	}
	s := defaultSettings()
	if err := yaml.Unmarshal(data, &s); err != nil {
		return defaultSettings()
	}
	// Migrate old settings: ensure minimizeTo has a valid value
	if s.MinimizeTo != "taskbar" && s.MinimizeTo != "tray" {
		s.MinimizeTo = "taskbar"
	}
	return s
}

// SaveSettings persists settings to disk.
func (a *App) SaveSettings(jsonStr string) error {
	// Start with existing settings to preserve fields not in the JSON (sidebar widths, etc.)
	s := a.GetSettings()
	if err := json.Unmarshal([]byte(jsonStr), &s); err != nil {
		return fmt.Errorf("invalid settings: %w", err)
	}

	data, err := yaml.Marshal(&s)
	if err != nil {
		return fmt.Errorf("marshal settings: %w", err)
	}

	dir := telaConfigDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	if err := os.WriteFile(settingsPath(), data, 0600); err != nil {
		return fmt.Errorf("write settings: %w", err)
	}

	return nil
}

// SaveSidebarWidth persists the profiles sidebar width.
func (a *App) SaveSidebarWidth(width int) {
	s := a.GetSettings()
	s.SidebarWidth = width
	data, _ := yaml.Marshal(&s)
	os.WriteFile(settingsPath(), data, 0600)
}

// SaveHubsSidebarWidth persists the hubs sidebar width.
func (a *App) SaveHubsSidebarWidth(width int) {
	s := a.GetSettings()
	s.HubsSidebarWidth = width
	data, _ := yaml.Marshal(&s)
	os.WriteFile(settingsPath(), data, 0600)
}

// GetCLIPath returns the path to the tela CLI binary.
func (a *App) GetCLIPath() string {
	path := a.findTool("tela")
	if path == "" {
		return "not installed"
	}
	return path
}

// ClearCredentialStore deletes the credential store file.
func (a *App) ClearCredentialStore() error {
	credPath := credstore.UserPath()
	if _, err := os.Stat(credPath); os.IsNotExist(err) {
		return nil
	}
	if err := os.Remove(credPath); err != nil {
		return fmt.Errorf("remove credential store: %w", err)
	}
	a.logCommand("Clear credential store", "rm "+credPath)
	return nil
}

// ImportProfile opens a file dialog and reads a profile YAML, replacing the current profile.
func (a *App) ImportProfile() error {
	dialog, err := wailsRuntime.OpenFileDialog(a.ctx, wailsRuntime.OpenDialogOptions{
		Title: "Import Profile",
		Filters: []wailsRuntime.FileFilter{
			{DisplayName: "YAML Files", Pattern: "*.yaml;*.yml"},
			{DisplayName: "All Files", Pattern: "*.*"},
		},
	})
	if err != nil {
		return fmt.Errorf("dialog failed: %w", err)
	}
	if dialog == "" {
		return nil // user cancelled
	}

	data, err := os.ReadFile(dialog)
	if err != nil {
		return fmt.Errorf("read profile: %w", err)
	}

	// Validate that it parses as a profile with valid content.
	var profile Profile
	if err := yaml.Unmarshal(data, &profile); err != nil {
		return fmt.Errorf("invalid profile YAML: %w", err)
	}
	for i, conn := range profile.Connections {
		if conn.Hub == "" {
			return fmt.Errorf("connection %d: hub is required", i+1)
		}
		if conn.Machine == "" {
			return fmt.Errorf("connection %d: machine is required", i+1)
		}
		for j, svc := range conn.Services {
			if svc.Local < 0 || svc.Local > 65535 {
				return fmt.Errorf("connection %d service %d: invalid local port %d", i+1, j+1, svc.Local)
			}
			if svc.Remote < 0 || svc.Remote > 65535 {
				return fmt.Errorf("connection %d service %d: invalid remote port %d", i+1, j+1, svc.Remote)
			}
		}
	}

	dir := profilesDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create profiles dir: %w", err)
	}

	if err := os.WriteFile(profilePath(), data, 0600); err != nil {
		return fmt.Errorf("write profile: %w", err)
	}

	return nil
}

// ExportProfile opens a save dialog and writes the current profile YAML.
func (a *App) ExportProfile() error {
	data, err := os.ReadFile(profilePath())
	if err != nil {
		return fmt.Errorf("no profile to export: %w", err)
	}

	dialog, err := wailsRuntime.SaveFileDialog(a.ctx, wailsRuntime.SaveDialogOptions{
		DefaultFilename: "telavisor-profile.yaml",
		Title:           "Export Profile",
		Filters: []wailsRuntime.FileFilter{
			{DisplayName: "YAML Files", Pattern: "*.yaml;*.yml"},
			{DisplayName: "All Files", Pattern: "*.*"},
		},
	})
	if err != nil {
		return fmt.Errorf("dialog failed: %w", err)
	}
	if dialog == "" {
		return nil // user cancelled
	}

	if err := os.WriteFile(dialog, data, 0600); err != nil {
		return fmt.Errorf("save profile: %w", err)
	}

	return nil
}

// ── Remote management ─────────────────────────────────────────────

type RemoteInfo struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type telaConfig struct {
	Remotes map[string]remoteEntry `yaml:"remotes,omitempty"`
}

type remoteEntry struct {
	URL          string `yaml:"url"`
	Token        string `yaml:"token,omitempty"`
	HubDirectory string `yaml:"hub_directory,omitempty"`
}

func telaConfigPath() string {
	return filepath.Join(telaConfigDir(), "config.yaml")
}

func loadTelaConfig() telaConfig {
	var cfg telaConfig
	data, err := os.ReadFile(telaConfigPath())
	if err != nil {
		cfg.Remotes = make(map[string]remoteEntry)
		return cfg
	}
	yaml.Unmarshal(data, &cfg)
	if cfg.Remotes == nil {
		cfg.Remotes = make(map[string]remoteEntry)
	}
	return cfg
}

func saveTelaConfig(cfg telaConfig) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	dir := filepath.Dir(telaConfigPath())
	os.MkdirAll(dir, 0700)
	return os.WriteFile(telaConfigPath(), data, 0600)
}

// ListRemotes returns all configured hub directory remotes.
func (a *App) ListRemotes() []RemoteInfo {
	cfg := loadTelaConfig()
	var result []RemoteInfo
	for name, entry := range cfg.Remotes {
		result = append(result, RemoteInfo{Name: name, URL: entry.URL})
	}
	return result
}

// AddRemote adds a hub directory remote.
func (a *App) AddRemote(name, url string) error {
	if name == "" || url == "" {
		return fmt.Errorf("name and URL are required")
	}
	cfg := loadTelaConfig()
	cfg.Remotes[name] = remoteEntry{URL: url}
	a.logCommand("Add remote", "tela remote add "+name+" "+url)
	return saveTelaConfig(cfg)
}

// RemoveRemote removes a hub directory remote.
func (a *App) RemoveRemote(name string) error {
	cfg := loadTelaConfig()
	if _, ok := cfg.Remotes[name]; !ok {
		return fmt.Errorf("remote %q not found", name)
	}
	delete(cfg.Remotes, name)
	a.logCommand("Remove remote", "tela remote remove "+name)
	return saveTelaConfig(cfg)
}

// ── Credential management ─────────────────────────────────────────

type CredentialInfo struct {
	HubURL   string `json:"hubUrl"`
	Identity string `json:"identity"`
}

// ListCredentials returns all stored hub credentials.
func (a *App) ListCredentials() []CredentialInfo {
	credPath := credstore.UserPath()
	store, err := credstore.Load(credPath)
	if err != nil {
		return []CredentialInfo{}
	}
	var result []CredentialInfo
	for url, cred := range store.Hubs {
		result = append(result, CredentialInfo{HubURL: url, Identity: cred.Identity})
	}
	return result
}

// RemoveCredential removes a single hub credential.
func (a *App) RemoveCredential(hubURL string) error {
	credPath := credstore.UserPath()
	store, err := credstore.Load(credPath)
	if err != nil {
		return fmt.Errorf("load credential store: %w", err)
	}
	if _, ok := store.Hubs[hubURL]; !ok {
		return fmt.Errorf("no credential for %s", hubURL)
	}
	delete(store.Hubs, hubURL)
	a.logCommand("Remove credential", "tela logout "+hubURL)
	return store.Save(credPath)
}

// ── Service management ────────────────────────────────────────────

// InstallAsService installs the current profile as an OS service.
func (a *App) InstallAsService() (string, error) {
	profilePath := profilePath()
	if _, err := os.Stat(profilePath); os.IsNotExist(err) {
		return "", fmt.Errorf("no profile to install (save a profile first)")
	}
	telaPath := a.findTool("tela")
	if telaPath == "" {
		return "", fmt.Errorf("tela binary not found")
	}
	cmd := exec.Command(telaPath, "service", "install", "-config", profilePath)
	hideConsoleWindow(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s: %s", err, string(out))
	}
	a.logCommand("Install service", telaPath+" service install -config "+profilePath)
	return strings.TrimSpace(string(out)), nil
}

// UninstallService removes the tela client OS service.
func (a *App) UninstallService() (string, error) {
	telaPath := a.findTool("tela")
	if telaPath == "" {
		return "", fmt.Errorf("tela binary not found")
	}
	cmd := exec.Command(telaPath, "service", "uninstall")
	hideConsoleWindow(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s: %s", err, string(out))
	}
	a.logCommand("Uninstall service", telaPath+" service uninstall")
	return strings.TrimSpace(string(out)), nil
}

// GetServiceStatus returns the tela client service status.
func (a *App) GetServiceStatus() string {
	telaPath := a.findTool("tela")
	if telaPath == "" {
		return "not installed"
	}
	cmd := exec.Command(telaPath, "service", "status")
	hideConsoleWindow(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "not installed"
	}
	return strings.TrimSpace(string(out))
}

// ServiceStart starts the tela client OS service.
func (a *App) ServiceStart() (string, error) {
	telaPath := a.findTool("tela")
	if telaPath == "" {
		return "", fmt.Errorf("tela binary not found")
	}
	cmd := exec.Command(telaPath, "service", "start")
	hideConsoleWindow(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s: %s", err, string(out))
	}
	a.logCommand("Start service", telaPath+" service start")
	return strings.TrimSpace(string(out)), nil
}

// ServiceStop stops the tela client OS service.
func (a *App) ServiceStop() (string, error) {
	telaPath := a.findTool("tela")
	if telaPath == "" {
		return "", fmt.Errorf("tela binary not found")
	}
	cmd := exec.Command(telaPath, "service", "stop")
	hideConsoleWindow(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%s: %s", err, string(out))
	}
	a.logCommand("Stop service", telaPath+" service stop")
	return strings.TrimSpace(string(out)), nil
}

// waitForProcessExit polls until the tela process is no longer tracked,
// or until the timeout expires.
func (a *App) waitForProcessExit(timeout time.Duration) {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		a.mu.Lock()
		proc := a.telaProcess
		conn := a.connected
		a.mu.Unlock()
		if proc == nil && !conn {
			return
		}
		time.Sleep(100 * time.Millisecond)
	}
}

// --- Helpers ---

func toWSURL(hubURL string) string {
	if strings.HasPrefix(hubURL, "https://") {
		return "wss://" + strings.TrimPrefix(hubURL, "https://")
	}
	if strings.HasPrefix(hubURL, "http://") {
		return "ws://" + strings.TrimPrefix(hubURL, "http://")
	}
	if !strings.HasPrefix(hubURL, "wss://") && !strings.HasPrefix(hubURL, "ws://") {
		return "wss://" + hubURL
	}
	return hubURL
}
